feat(PPDSC-2032): feat-ppdse-2032-audio-player-time-display
newscorp-ghfb/newskit pull request #103
Opened 2022-03-03 13:54 UTC by baburay23

PPDSC-2032

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
 - [ ] Written unit tests against changes
 - [ ] Written accessibility tests against the component
 - [ ] Written functional tests against the component and/or NewsKit site
 - [ ] Updated relevant documentation
 - [ ] Updated the release notes for the [next release version](https://nidigitalsolutions.jira.com/wiki/spaces/NPP/pages/2349695021/Release%2BNotes%2BCode%2B-%2BWeb%2BDocumentation)
 - [ ] Discussed with QA and/or design about any visual changes

**I have tested manually:**
 - [ ] Renders correctly on IE11
 - [ ] The feature's functionality is working as expected on other browsers such as Safari, Firefox and IE11
 - [ ] There are no accessibility errors reported by WAVE
 - [ ] The screen reader reads the expected text for the tabbable elements.
 - [ ] There are no new errors in the browser console coming from this PR.
 - [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
 - [ ] The Playground feature is working as expected

**Before**

**After:**

**Who should review this PR**

**How to test**

2022-03-11 08:58 UTC, mutebg commented on src/audio-player-composable/components/time-display/time-display.tsx
> +    <TimeDisplayContainer>
Why do we use Label here? IMO that is not the semantic HTML tag, Label is used to describe input element and in our case do not have a such. Its better to use TextBlock as "span"

2022-03-11 08:58 UTC, mutebg commented on src/audio-player-composable/components/time-display/time-display.tsx
> +    <TimeDisplayContainer>
Why do we use Label here? IMO that is not the semantic HTML tag, Label is used to describe input element and in our case do not have a such. Its better to use TextBlock as "span" and we do that we can remove `TimeDisplayContainer` and pass stylePreset and typographyPreset directly on it.

2022-03-11 08:58 UTC, mutebg commented on src/audio-player-composable/audio-player-composable.tsx
> +    currentTime: trackPositionArr[0],
@Xin00163 in your ticket this variable is named trackPosition but here is named: currentTime, maybe we should keep naming consistent in both functions.

2022-03-11 09:08 UTC, Vanals commented on src/audio-player-composable/components/time-display/time-display.tsx
> +    <TimeDisplayContainer>
Yeah. agree!

2022-03-11 09:11 UTC, Vanals commented on src/audio-player-composable/audio-player-composable.tsx
> +    currentTime: trackPositionArr[0],
I personally would prefer keeping currentTime for the "label", more clear on what it is for, in the getTimeDisplay, there is not literally any track position

2022-03-11 09:14 UTC, Vanals commented on src/audio-player-composable/__tests__/utils.test.tsx
>  //     expect(
is this a left over?

2022-03-11 09:15 UTC, mutebg commented on src/audio-player-composable/audio-player-composable.tsx
> +    currentTime: trackPositionArr[0],
@Vanals I agree, that's why my suggestion is updating trackPosition to currentTime in Xin's ticket. In reality, track position is calculated based on currentTime and duration.

2022-03-11 16:25 UTC, baburay23 commented on src/audio-player-composable/components/time-display/time-display.tsx
> +    <TimeDisplayContainer>
ah sorry i have now changed it to TextBlock however when i use `TextBlock as "span" ` without seekBa
<img width="555" alt="Screenshot 2022-03-11 at 15 37 42" src="https://user-images.githubusercontent.com/54642337/157907285-526a062f-d75c-4b81-8820-e85f5dbe1f8f.png">
r

2022-03-11 16:30 UTC, baburay23 commented on src/audio-player-composable/components/time-display/style-presets.ts
> +  },
i did this because in [figma ](https://www.figma.com/file/FSbCQa6SzVR3K48ZWLeD77/branch/KVZQUwYoA0WqA289Y7LGHu/%F0%9F%9F%A2-NK-Web-Components?node-id=2151%3A0)

2022-03-14 06:14 UTC, mutebg commented on src/audio-player-composable/components/time-display/time-display.tsx
> +    <TimeDisplayContainer>
that's an interesting case, in general, it does not matter a lot since it's very likely this to be used together with GridLayout or Stack component in order to build the whole audio player. 
Maybe you can change the display: to inline-block using styled TextBlock

2022-03-14 06:41 UTC, mutebg commented on src/audio-player-composable/components/time-display/time-display.tsx
> +  ${getTypographyPreset(`timeDisplay.container`, '')};
I think these paths are wrong, since we don't have container anymore:
```
${getStylePreset(`timeDisplay`, '')};
 ${getTypographyPreset(`timeDisplay`, '')};
 ```

2022-03-14 06:41 UTC, mutebg commented on src/audio-player-composable/components/time-display/style-presets.ts
>    container: {
should this be the opposite?  you need to remove the container and leave the currentTimeDisplay?

2022-03-14 06:41 UTC, mutebg commented on src/audio-player-composable/audio-player-composable.tsx
> +    trackPosition,
I know this is not part of your ticket but if @Vanals and @Xin00163 agree with that let's rename trackPosition to currentTime so its consistent between both getter functions

2022-03-14 06:41 UTC, mutebg commented on src/audio-player-composable/components/time-display/defaults.ts
> +  },
This default file should be updated, if we have only TextBlock probably should like like
```
timeDisplay: {
  stylePreset: 'currentTimeDisplay',
}
```
and why there is not default typography preset?

2022-03-14 06:48 UTC, mutebg commented on src/audio-player-composable/context.tsx
Since this is the kind of the last ticket before release, can we update useAudioPlayerContext to look like the menu context hook, so that customers have a warning if they try to use audio components outside audio context.
```
export const useAudioPlayerContext = () => {
  const context = useContext(AudioPlayerContext);

  /* istanbul ignore if */
  if (
    process.env.NODE_ENV !== 'production' &&
    Object.keys(context).length === 0
  ) {
    // eslint-disable-next-line no-console
    console.error(
      'You are using a component which needs to be a child of <AudioPlayerComposable />',
    );
  }

  return context;
};

```

2022-03-14 09:52 UTC, baburay23 commented on src/audio-player-composable/components/time-display/style-presets.ts
>    container: {
sorry for the confusion i now only have one style preset
```
 timeDisplay: {
    base: {
      backgroundColor: '{{colors.transparent}}',
    },
  },
```
and i have added typographyPreset to the defaults

2022-03-14 10:05 UTC, baburay23 commented on src/audio-player-composable/components/time-display/time-display.tsx
> +    <TimeDisplayContainer>
cool i have changed it back to span and added in `display: to inline-block `

2022-03-15 05:41 UTC, mutebg reviewed
Shall we add prefix name to all all audio-player components,
for example all form related are FormInputSelect, FormInputCheckbox, FormInputTextField.
SeekBar -> AudioPlayerSeekBar
PlayPauseButton -> AudioPlayerPlayPauseButton and so on
@Vanals @Xin00163 @pdimova  what you think?

2022-03-15 05:41 UTC, mutebg commented on src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
> +        columnGap="16px"
can we use a token here, should be `space040`

2022-03-15 05:41 UTC, mutebg commented on src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
> +        />
Just to simplify it, can we remove the onClick event

2022-03-15 05:41 UTC, mutebg commented on src/audio-player-composable/audio-player-composable.tsx
> +    currentTime,
if you rename trackPosition to currentTime my suggestion is to rename setTrackPosition and trackPositionRef.

2022-03-15 05:41 UTC, mutebg commented on src/audio-player-composable/components/time-display/time-display.tsx
> +  display: inline-block;
Maybe I made a mistake with that suggestion, 
Probably we should keep the component as a div and remove the display: inline-block.
as far I am aware all components we produce have a width of 100%.
Lets ask Mike about this

2022-03-15 05:41 UTC, mutebg commented on src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
> +      </GridLayout>
I am not sure what is this GridLayout doing, can you elaborate please

2022-03-15 05:41 UTC, mutebg commented on src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
> +      <GridLayout columns="repeat(1, 1fr)">
same here

2022-03-15 10:15 UTC, baburay23 commented on src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
> +        />
i have removed from all stories just left it on the playPauseButton story

2022-03-15 11:13 UTC, baburay23 commented on src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
> +      </GridLayout>
hey, I was trying to display the time at the start for this one. I see that with using justifySelf="start"  I was able to apply
`<TimeDisplay format={({currentTime}) => calculateTime(currentTime)} />` at the start and design wanted it to be in a grid. Is there a better way to do this? After what you showed me yesterday i tried to use it without `<GridLayoutItem/>` but i need to just wrap the <TimeDisplay/> component which is why i used it. 
I noticed that if i dont use `<GridLayoutItem/>` the colour jumps out
<img width="710" alt="Screenshot 2022-03-15 at 11 13 01" src="https://user-images.githubusercontent.com/54642337/158365819-d3c9b829-2de8-4034-9325-6cb09c632d86.png">

2022-03-15 11:15 UTC, baburay23 commented on src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
> +      <GridLayout columns="repeat(1, 1fr)">
i was trying to do the same thing as above just place the <TimeDisplay/> at the start or end of the seek bar

2022-03-15 11:45 UTC, baburay23 commented on src/audio-player-composable/components/time-display/time-display.tsx
> +  display: inline-block;
I spoke to Mike  and he said since its kinda unlikely they would use the time stamp on its own it does not really matter. but he gave his opinion of using span

2022-03-15 14:53 UTC, baburay23 commented on src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
> +      </GridLayout>
just fyi for anyone else  Since we are using span i have added in display: block; into the styled <TextBlock/> so the component should be at 100% width if it is not wrapped in a grid/stack etc (have spoken to Mike about this as well)

2022-03-15 15:25 UTC, mutebg requested changes

2022-03-15 15:25 UTC, mutebg commented on src/audio-player-composable/components/time-display/defaults.ts
> +  timeDisplay: {
I am afraid that we need to add prefix to all defaults 
timeDisplay -> audioPlayerTimeDisplay
seekBar -> audioPlayerSeekBar

the reason is that at the moment we add volume control it will clash with our current volumeControl defaults

2022-03-16 05:53 UTC, mutebg commented on src/audio-player-composable/components/seek-bar/seek-bar.tsx
> +  console.log(seekBarSliderDefaults);
remove the console.log

2022-03-16 05:53 UTC, mutebg commented on src/audio-player-composable/components/time-display/time-display.tsx
> +  ${getTypographyPreset(`timeDisplay`, '')};
you need to update these 2 paths

2022-03-16 09:23 UTC, mutebg approved these changes

2022-03-16 09:44 UTC, mutebg submitted a review, later dismissed

2022-03-16 11:25 UTC, Vanals commented on src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
> +import {AudioPlayerTimeDisplay} from '../components/time-display/time-display';
if we have an index.js we should be able to do 
```'../components/time-display```
 without repetition, same for the other imports

2022-03-16 12:29 UTC, mutebg commented on .next/package.json
> +{"type": "commonjs"}
can you remove this file, apparently it appears sometime

2022-03-16 12:56 UTC, mutebg approved these changes

2022-03-17 08:41 UTC, Vanals commented on src/audio-player-composable/context.tsx
> +
How will this work? in which scenarios this error will trigger 🤔 ?
This line `Object.keys(context).length === 0` seems to be key but I don't get it

2022-03-17 08:43 UTC, Vanals approved these changes

2022-03-17 08:43 UTC, mutebg commented on src/audio-player-composable/context.tsx
> +
this error will be shown when you run code in dev mode and you are trying to use a component out of the context

2022-03-17 10:58 UTC, merged