feat(PPDSC-2020): add radio-button and group
newscorp-ghfb/newskit pull request #109
Opened 2022-03-08 11:44 UTC by mutebg

PPDSC-2020

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
 - [ ] Written unit tests against changes
 - [ ] Written accessibility tests against the component
 - [ ] Written functional tests against the component and/or NewsKit site
 - [ ] Updated relevant documentation
 - [ ] Updated the release notes for the [next release version](https://nidigitalsolutions.jira.com/wiki/spaces/NPP/pages/2349695021/Release%2BNotes%2BCode%2B-%2BWeb%2BDocumentation)
 - [ ] Discussed with QA and/or design about any visual changes

**I have tested manually:**
 - [ ] Renders correctly on IE11
 - [ ] The feature's functionality is working as expected on other browsers such as Safari, Firefox and IE11
 - [ ] There are no accessibility errors reported by WAVE
 - [ ] The screen reader reads the expected text for the tabbable elements.
 - [ ] There are no new errors in the browser console coming from this PR.
 - [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
 - [ ] The Playground feature is working as expected

**Before**

**After:**

**Who should review this PR**

**How to test**

2022-03-09 06:45 UTC, newskit-engineering commented
You can preview these changes on: 
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2020-radio-button 
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2020-radio-button/storybook

2022-03-14 10:36 UTC, Vanals commented on site/pages/components/radio-button.tsx
> +      description: 'TODO',
Is this going to be done in another ticket?

2022-03-14 10:42 UTC, Vanals commented on src/radio-button/__tests__/radio-button.stories.tsx
> +        <label htmlFor="no-label">without label</label>
Does it make sense to show this example in our storybook? As it is not a practice I think we should suggest 😬

2022-03-14 10:44 UTC, Vanals commented on src/switch-base/switch-base.tsx
> +export const SwitchBase = React.forwardRef<HTMLInputElement, SwitchBaseProps>(
I wonder if there could be a more neutral name for this? As a new dev, I would be wondering why we are using a "Switch base" for a checkbox 🤔

2022-03-14 10:47 UTC, mutebg commented on src/switch-base/switch-base.tsx
> +export const SwitchBase = React.forwardRef<HTMLInputElement, SwitchBaseProps>(
I believe I copied the name from Material-UI, they use the same approach, having 1 base component that is responsible for toggle, checkbox and radio. BUT any suggestions are welcome

2022-03-14 10:48 UTC, mutebg commented on src/radio-button/__tests__/radio-button.stories.tsx
> +        <label htmlFor="no-label">without label</label>
We just want to show this is possible, we have the same example for the Checkbox. I agree that is not best practice but for sure there are some cases that you want to use custom label

2022-03-14 12:05 UTC, mutebg commented on site/pages/components/radio-button.tsx
> +      description: 'TODO',
thanks, updated it

2022-03-15 06:10 UTC, mutebg commented on src/radio-button/radio-group.tsx
> +        <div ref={ref} role="radiogroup">
I see, from what I read seems very similar to Fieldset and legend, wondering if just update examples to use Fiedlset & Legend since is better practice

2022-03-15 08:10 UTC, Vanals commented on src/radio-button/radio-group.tsx
> +        <div ref={ref} role="radiogroup">
You are right, I missed it, let's follow the best practice pointed by Aysha and implement it

2022-03-15 10:13 UTC, mutebg commented on src/radio-button/radio-group.tsx
> +        <div ref={ref} role="radiogroup">
From what I see here, role="radiogroup" and aria-labelledBy are only used when you DO not use fieldset.
https://dequeuniversity.com/library/aria/radio-and-radio-group

I added fieldset and legend in our storybook examples

2022-03-15 17:47 UTC, pdimova commented on src/switch-base/switch-base.tsx
> +      if (ref && ref.current && !label) {
how about checkig first for the existance of the label `!label && ref && ref.current` ?

2022-03-15 17:47 UTC, pdimova commented on src/switch-base/switch-base.tsx
> +    const onFeedbackClick = useCallback(() => {
can you please move this function next to the other onFeedback.. callbacks?

2022-03-15 17:47 UTC, pdimova commented on src/switch-base/switch-base.tsx
> +            isHover={isFeedbackHover || isLabelHover}
`isHovered` ?

2022-03-15 17:49 UTC, pdimova requested changes
Hit the Comment button by mistake :)

2022-03-15 21:52 UTC, pdimova commented on src/utils/hooks/use-controlled.ts
>    const setValueIfUncontrolled = React.useCallback(
Do you know why the following checked boxes can not be unchecked?
![Screenshot 2022-03-15 at 23 49 49](https://user-images.githubusercontent.com/16742525/158478749-c9d91c65-a96c-4c28-9f80-3d3480274cb1.png)

2022-03-16 05:57 UTC, mutebg commented on src/switch-base/types.ts
> +  defaultSwitchComponent: React.ComponentType<SwitchBaseIconProps>;
what about `defaultSwitchIconComponent` but in the same time it does not have to be an icon, you can pass whatever you want here think in the context of toggle

2022-03-16 06:07 UTC, mutebg commented on src/switch-base/switch-base.tsx
> +        {labelPosition === 'start' && labelElement}
good one

2022-03-16 06:08 UTC, mutebg commented on src/switch-base/switch-base.tsx
> +      if (ref && ref.current && !label) {
makes sense

2022-03-16 06:20 UTC, mutebg commented on src/switch-base/switch-base.tsx
> +            feedbackIsVisible={isLabelHover || isFeedbackHover || isFocused}
Since we are using z-index to stack feedback, custom icon and input on each other, when you have 2 checkboxes to each other ( or different components with zIndex ) we change the zIndex of the active one ( focused/hovered) so that it goes on top of its siblings.
<img width="259" alt="Screenshot 2022-03-16 at 8 18 39" src="https://user-images.githubusercontent.com/3543332/158528502-505865f9-e969-46c3-8715-65dc5aaad28e.png">

I might try to rewrite this part with GridLayout to see if things are better

2022-03-16 06:22 UTC, mutebg commented on src/switch-base/styled.tsx
> +  ${({size, labelPosition, path}) =>
I am not sure, assuming the user will provide its own label, but I can ask Mike about that.

2022-03-16 06:26 UTC, mutebg commented on src/switch-base/switch-base.tsx
> +        onMouseOver={onLabelMouseOver}
it does not matter the size, since the Feedback is inside so it works correctly, I want to know when the whole element is hovered

2022-03-16 06:28 UTC, mutebg commented on src/switch-base/switch-base.tsx
> +    const [isFocused, setFocused] = React.useState(false);
good one

2022-03-16 06:31 UTC, mutebg commented on src/utils/hooks/use-controlled.ts
>    const setValueIfUncontrolled = React.useCallback(
because they are controlled like so => `<Checkbox checked />` if you want these to be uncontrolled they need to change to defaultChecked

2022-03-16 06:53 UTC, mutebg commented on src/switch-base/switch-base.tsx
> +            <CheckIcon {...(checkIconProps as SwitchBaseIconProps)} />
I am not sure why I would need that, checked is part of checkIconProps and CheckIcon is DefaultCheckboxIcon so that component will receive the props and will decide what to render. I hope managed to explain it

2022-03-16 08:36 UTC, Vanals commented on src/radio-button/radio-group.tsx
> +        <div ref={ref} role="radiogroup">
Sounds good, just test is read nicely I guess.

2022-03-16 08:42 UTC, Vanals commented on src/radio-button/radio-button.tsx
> +  ) : null;
```suggestion
  checked &&
    <IconFilledCircle
      overrides={{
        size: iconSize,
        ...overrides,
      }}
    />
```

Something like that should work and we do not need any ternary. Not sure if needs to be wrapped in a { }.

2022-03-16 08:47 UTC, mutebg commented on src/radio-button/radio-group.tsx
> +        <div ref={ref} role="radiogroup">
I added fieldset to all radio scenarios where make sense, SR is reading everything as expected !

2022-03-16 08:47 UTC, Vanals commented
As discussed yesterday can we also add the focus state for checkbox and radio? at least a basic one. As might take long before we do something global for more standardized the focus states in all the comps

2022-03-16 08:48 UTC, Vanals commented on src/radio-button/radio-group.tsx
> +        <div ref={ref} role="radiogroup">
oks! good one

2022-03-16 09:07 UTC, pdimova commented on src/switch-base/types.ts
> +  defaultSwitchComponent: React.ComponentType<SwitchBaseIconProps>;
maybe `defaultSwitchSelectorComponent` ?  https://miro.medium.com/max/1400/1*hFnStDBZVapwC98Gh25NaQ.png

2022-03-16 09:12 UTC, pdimova commented on src/switch-base/switch-base.tsx
> +            <CheckIcon {...(checkIconProps as SwitchBaseIconProps)} />
in both files `checkbox.tsx` and `radio-button.tsx `you have repeating code:

```
  **checked** ? (
    <IconFilledCheck ..... />
  ) : null;
```

Maybe we can have the check expression in a single place?

2022-03-16 09:14 UTC, pdimova commented on src/switch-base/styled.tsx
> +  ${({size, labelPosition, path}) =>
it is  just an empty space if a label is missing

2022-03-16 09:19 UTC, pdimova commented on src/utils/hooks/use-controlled.ts
>    const setValueIfUncontrolled = React.useCallback(
It's not so intuitive in my opinion. A user will just provide a `checked` attribute to the Element and will expect to be able to unselect/uncheck this element.

2022-03-16 09:32 UTC, mutebg commented on src/switch-base/switch-base.tsx
> +            <CheckIcon {...(checkIconProps as SwitchBaseIconProps)} />
that is not exactly true. these icons are overridable, that means can pass your custom component in overrides.
const MyIcon = ({checked}) => checked ? 'yes' : 'no';
<Checkbox overrides={{icon: MyIcon}} /> 
and in the way we do that is via getComponentOverrides so we need that to be repeated in both places, in reality is not repetition.

2022-03-16 10:00 UTC, mutebg commented on src/switch-base/styled.tsx
> +  ${({size, labelPosition, path}) =>
spoke with Mike
Probably if some one uses it without label, they will provide its own label: 
```
<Checkbox /> <label>custom one</label>
```
and in that case, they will need that margin, ( otherwise have to use grid/stack to add space in between )
and when they don't need that space always can override it vie the overrides

2022-03-16 10:28 UTC, mutebg commented on src/radio-button/radio-button.tsx
> +  ) : null;
it will not work since that will return undefined when checked is false, that is not valid react component

2022-03-16 10:33 UTC, mutebg commented on src/utils/hooks/use-controlled.ts
>    const setValueIfUncontrolled = React.useCallback(
that is how the native HTML inputs work, that's why we align with it.
Example -> https://codesandbox.io/s/rough-snow-ppq4r9?file=/src/App.js

2022-03-16 11:09 UTC, mutebg commented on src/switch-base/switch-base.tsx
> +    const onFeedbackClick = useCallback(() => {
onFeedbackMouse* been removed so this can stay here

2022-03-16 11:10 UTC, mutebg commented on src/switch-base/switch-base.tsx
> +            feedbackIsVisible={isLabelHover || isFeedbackHover || isFocused}
GridLayout change will require a huge rewrite I am not sure if we want to spend another few days doing that

2022-03-16 11:11 UTC, mutebg commented on src/switch-base/switch-base.tsx
> +        onMouseOver={onLabelMouseOver}
onFeedbackMouseOver/Leave been removed since they are not used anymore ( design changed )

2022-03-16 14:12 UTC, pdimova commented on src/radio-button/__tests__/radio-button.stories.tsx
> +        <label htmlFor="no-label">without label</label>
this is actually a custom label example instaed if no-label one

2022-03-16 15:18 UTC, mutebg commented on src/switch-base/styled.tsx
> +    isHovered: boolean;
It's been updated already, do you see something additional that needs updating?

2022-03-16 15:21 UTC, pdimova commented on src/switch-base/styled.tsx
> +    isHovered: boolean;
<img width="396" alt="Screenshot 2022-03-16 at 15 19 00" src="https://user-images.githubusercontent.com/16742525/158625235-8477acc3-b813-44af-ac84-6bacadce2500.png">
 sorry, forgot the attachment

2022-03-16 15:22 UTC, mutebg commented on src/radio-button/radio-button.tsx
> +const ThemelessCheckbox = React.forwardRef<HTMLInputElement, RadioButtonProps>(
copy paste development :)

2022-03-16 15:23 UTC, mutebg commented on src/radio-button/__tests__/radio-button.stories.tsx
> +              <RadioButton size={size} label={size} checked={false} />
no, removed it

2022-03-17 07:50 UTC, pdimova submitted a review, later dismissed

2022-03-17 12:03 UTC, Vanals approved these changes

2022-03-17 14:51 UTC, pdimova approved these changes

2022-03-18 06:00 UTC, merged