feat(PPDSC-2009): add reduced motion to transitionPreset
newscorp-ghfb/newskit pull request #119
Opened 2022-03-17 08:58 UTC by Xin00163

PPDSC-2009

- Refactor `getTransitionPresetFromTheme` so that it will render both `no-preference` and `reduce` media queries.
- Change transitionDuration to 0 if motion is reduced

**I have done:**
 - [x] Written unit tests against changes
 - [ ] Written accessibility tests against the component
 - [ ] Written functional tests against the component and/or NewsKit site
 - [ ] Updated relevant documentation
 - [ ] Updated the release notes for the [next release version](https://nidigitalsolutions.jira.com/wiki/spaces/NPP/pages/2349695021/Release%2BNotes%2BCode%2B-%2BWeb%2BDocumentation)
 - [ ] Discussed with QA and/or design about any visual changes

**I have tested manually:**
 - [ ] Renders correctly on IE11
 - [ ] The feature's functionality is working as expected on other browsers such as Safari, Firefox and IE11
 - [ ] There are no accessibility errors reported by WAVE
 - [ ] The screen reader reads the expected text for the tabbable elements.
 - [ ] There are no new errors in the browser console coming from this PR.
 - [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
 - [ ] The Playground feature is working as expected

**Before**

**After:**

**Who should review this PR**

**How to test**

2022-03-17 09:05 UTC, newskit-engineering commented
You can preview these changes on: 
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2009-reduced-motion 
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2009-reduced-motion/storybook

2022-03-18 07:58 UTC, mutebg requested changes

2022-03-22 06:36 UTC, mutebg commented on src/utils/__tests__/get-transition-duration.test.ts
> +        exit: 2000,
I don't think that's the right behaviour, the way we use getTransitionDuration is inside JS ( React components )  to calculate the Transitions Timeout, so the function should just return a simple JS object or a number.  When you have MQ object it should just return the max values
@pdimova am I correct?

2022-03-22 09:14 UTC, Xin00163 commented on src/utils/__tests__/get-transition-duration.test.ts
> +        exit: 2000,
I think you are right. The returned value is for the timeout which won't recognise MQ

2022-03-23 08:10 UTC, mutebg submitted a review, later dismissed

2022-03-23 08:10 UTC, mutebg commented on src/utils/get-transition-duration.ts
> +        }
This is a bit of personal preference, you can write it like so:
```suggestion
      (acc, [, transitionPresetToken]) => {
        const tokensArray: string[] = isArrayLikeObject(transitionPresetToken)
          ? transitionPresetToken
          : [transitionPresetToken];

        const currentDuration = extractDurationFromPreset(
          tokensArray,
          props.theme,
        );
```

2022-03-23 09:13 UTC, Xin00163 commented on src/utils/get-transition-duration.ts
> +        }
This looks neat 🔥. Thanks!

2022-03-23 09:21 UTC, mutebg submitted a review, later dismissed

2022-03-24 05:36 UTC, mutebg approved these changes

2022-03-24 10:56 UTC, baburay23 approved these changes

2022-03-24 11:16 UTC, merged