feat(PPDSC-2039): audio player event handler
newscorp-ghfb/newskit pull request #127
Opened 2022-03-22 15:03 UTC by Xin00163

PPDSC-2039

Allow consumers to pass an extra function which would be called before our event handlers.

**I have done:**
 - [ ] Written unit tests against changes
 - [ ] Written accessibility tests against the component
 - [ ] Written functional tests against the component and/or NewsKit site
 - [ ] Updated relevant documentation
 - [ ] Updated the release notes for the [next release version](https://nidigitalsolutions.jira.com/wiki/spaces/NPP/pages/2349695021/Release%2BNotes%2BCode%2B-%2BWeb%2BDocumentation)
 - [ ] Discussed with QA and/or design about any visual changes

**I have tested manually:**
 - [ ] Renders correctly on IE11
 - [ ] The feature's functionality is working as expected on other browsers such as Safari, Firefox and IE11
 - [ ] There are no accessibility errors reported by WAVE
 - [ ] The screen reader reads the expected text for the tabbable elements.
 - [ ] There are no new errors in the browser console coming from this PR.
 - [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
 - [ ] The Playground feature is working as expected

**Before**

**After:**

**Who should review this PR**

**How to test**

2022-03-22 16:31 UTC, Vanals commented on src/audio-player-composable/audio-player-composable.tsx
> +          {...props}
Wonder if is better to destructure the event props ,it is then  going to be more readable and we avoid passing unnecessary/wrong attributes to the audio element. 

Same as we are doing with the `src`. I know they are many but I think is worth

2022-03-22 17:36 UTC, Xin00163 commented on src/audio-player-composable/audio-player-composable.tsx
> +          {...props}
Make sense to me. Have implemented the changes. Pls let me know if they look right

2022-03-23 09:43 UTC, Vanals approved these changes

2022-03-24 06:16 UTC, mutebg requested changes

2022-03-24 06:16 UTC, mutebg commented on src/audio-player-composable/audio-player-composable.tsx
> +    eventCallback ? eventCallback(e) : audioEvents![eventName](e);
this is slightly incorrect, we need to combine our internal audio event with the user-provided one if exist.
right now if I add onDurationChange it breaks the player.

In order to combine events you can use the util -> composeEventHandlers;
```
const eventHandler = (eventName: AudioEvents) => {
    const propEvent = props[eventName];
    const internalEvent = audioEvents[eventName];
    return composeEventHandlers([propEvent, internalEvent]);
  };
  ```

2022-03-25 10:23 UTC, mutebg commented on src/audio-player-composable/audio-player-composable.tsx
> +      ? composeEventHandlers([propEvent(e), internalEvent(e)])
```js
const eventHandler = (event) => {
    const propEvent = props[eventName];
    const internalEvent = audioEvents[eventName];
    return composeEventHandlers([propEvent, internalEvent])
```

2022-03-25 10:56 UTC, mutebg approved these changes

2022-03-25 10:57 UTC, Vanals submitted a review, later dismissed

2022-03-28 10:54 UTC, mutebg approved these changes

2022-03-28 10:59 UTC, Vanals approved these changes

2022-03-28 12:29 UTC, merged