docs(PPDSC-1903): Select page
newscorp-ghfb/newskit pull request #152
Opened 2022-04-08 04:28 UTC by Srinivasan-Ramasamy

PPDSC-1903

**What**

1. Created doc select page.

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-04-08 04:41 UTC, newskit-engineering commented
You can preview these changes on: 
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-1903-select-page 
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-1903-select-page/storybook

2022-04-12 11:18 UTC, baburay23 approved these changes

2022-04-13 04:26 UTC, mutebg requested changes

2022-04-13 04:26 UTC, mutebg commented on site/pages/components/select.tsx
> +    type: ['boolean'],
this is  `MQ<boolean>`

2022-04-13 04:26 UTC, mutebg commented on site/pages/components/select.tsx
> +    attribute: 'selectOption.spaceInline',
sorry but this is not correct, I guess the documentation in confluence is wrong

2022-04-13 04:26 UTC, mutebg commented on site/pages/components/select.tsx
> +  },
this is also not correct

2022-04-13 04:26 UTC, mutebg commented on site/pages/components/select.tsx
> +    attribute: 'selectOption.spaceInline',
there are 2 components: Select and SelectOption and they have their own overrides. I think the part with overrides and prop was correct

2022-04-13 06:00 UTC, Srinivasan-Ramasamy commented
Thanks @mutebg  and @baburay23 for reviewing the code :+1:

2022-04-13 06:00 UTC, Srinivasan-Ramasamy commented on site/pages/components/select.tsx
> +    type: ['boolean'],
Sure Stoyan, I've modified this.

2022-04-13 06:52 UTC, Srinivasan-Ramasamy commented on site/pages/components/select.tsx
> +  },
thanks @mutebg , I've updated the tables.

2022-04-14 04:46 UTC, mutebg approved these changes

2022-04-14 09:57 UTC, baburay23 approved these changes

2022-04-14 10:10 UTC, merged