feat(PPDSC-1982): layout props 2 of 6
newscorp-ghfb/newskit pull request #164
Opened 2022-04-14 14:02 UTC by Xin00163

PPDSC-1982

1. Add logical margin and padding support to the following components and provide storybook examples:

> Aspect Ratio (Do not need logical properties)
> Audio Player
> Banner
> Byline
> Caption (Caption will be rebuilt in https://nidigitalsolutions.jira.com/browse/PPDSC-2091)
> Card
> Checkbox (Radio Button is done as well)
> Date Time

2. Provide storybook examples for components in https://github.com/newscorp-ghfb/newskit/pull/84:
> Block
> TextBlock
> Stack
> Button
> Tabs
> AssistiveText
> Label
> Link
Select will be in a separate ticket.
3. Apply logical props to the sub-components if it has nested structure like the card.
4. Expand functions in logical-properties

There should be no visual changes to the components and no breaking changes.

**I have done:**
- [x] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-04-14 14:07 UTC, newskit-engineering commented
You can preview these changes on: 
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-1982-layout-props-2-of-6 
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-1982-layout-props-2-of-6/storybook

2022-04-18 09:13 UTC, mutebg requested changes

2022-04-18 09:13 UTC, mutebg commented on src/utils/logical-properties.ts
> +  overrides: any,
as I mentioned before you can try making this `object  | undefined`

2022-04-18 09:13 UTC, mutebg commented on src/banner/styled.tsx
> +        )};
I believe `spaceInline` prop is actually the `gap` between the icon and container here. so that props eventually need renaming. and eventually the code should look something like
```js
${({layout}) =>
    getResponsiveSpace(
      layout === 'vertical' ? 'marginBlockEnd' : 'marginInlineEnd',
      `banner.${layout}.content`,
      'content',
      'gap',
    )};
```

2022-04-20 10:42 UTC, Xin00163 commented on src/card/types.ts
> +    paddingInline?: MQ<string>;
They are used to replace `spaceInset`

2022-04-20 10:47 UTC, Xin00163 commented on src/base-switch/styled.tsx
> +        )}
Does it mean we should no try to use logical properties in this case?

2022-04-20 15:44 UTC, Xin00163 commented on src/banner/styled.tsx
> +        )};
Have removed the change and left a comment in the types.ts file

2022-04-20 16:30 UTC, Xin00163 commented
Should have addressed all the comments @mutebg. 
Some of the `spaceInline` & `spaceStack` properties are referring to the gap between two elements. As discussed with @mutebg, comments have been added to highlight those cases. When we are ready for a breaking change ticket, we could filter those comments and change the `spaceInline` & `spaceStack` property name to `gap` or other names.

I noticed that there are no unit tests for logical props added to first batch of components. I didn't add any either as I think logical-properties.test.ts should cover it. Let me know if you think they are needed.

2022-04-21 04:37 UTC, mutebg commented on src/card/types.ts
> +    paddingInlineEnd?: MQ<string>;
Can we just use `LogicalPadding` here ?

2022-04-21 08:25 UTC, Xin00163 commented on src/card/types.ts
> +    paddingInlineEnd?: MQ<string>;
OK. Will need to export this type

2022-04-22 12:05 UTC, Vanals commented on site/pages/components/aspect-ratio.mdx
> +# (deprecated) Aspect Ratio
Why are we deprecating it? Should we also explain it to the user/propose the alternative?

2022-04-22 12:06 UTC, Vanals commented on src/aspect-ratio/types.ts
> + * @deprecated AspectRatioProps is deprecated and will be removed in the next major release.
Do we need a ticket for removing it? 🤔

2022-04-22 12:15 UTC, Vanals commented on src/banner/types.ts
> +        spaceStack?: MQ<string>; // Note: spaceStack is used as a gap. Should rename this to gap instead of using logical props.
is this going to happen in future? when ready for the breaking change?

2022-04-22 12:19 UTC, Vanals commented on src/byline/byline.tsx
> +    )}
🧠

2022-04-22 12:35 UTC, Xin00163 commented on src/banner/types.ts
> +        spaceStack?: MQ<string>; // Note: spaceStack is used as a gap. Should rename this to gap instead of using logical props.
Yes, we will do this in a separate ticket when we are ready for a breaking change.

2022-04-22 12:35 UTC, Xin00163 commented on src/aspect-ratio/types.ts
> + * @deprecated AspectRatioProps is deprecated and will be removed in the next major release.
It was decided that I should do it in this ticket.

2022-04-22 12:38 UTC, Xin00163 commented on site/pages/components/aspect-ratio.mdx
> +# (deprecated) Aspect Ratio
It was decided in yesterday's tech analysis as this component is not used. Maybe I should point the user to the `getAspectRatioStyles` util function used in images?

2022-04-26 10:21 UTC, Vanals commented on site/pages/components/aspect-ratio.mdx
> +# (deprecated) Aspect Ratio
Yes I think we should 👍

2022-04-27 09:11 UTC, Xin00163 commented on site/pages/components/aspect-ratio.mdx
> +# (deprecated) Aspect Ratio
I think this should be done in a different ticket if we think there is a need. `getAspectRatioStyles` is an internal util function at the moment. The thing is we do not think there is a use case for users to use `AspectRatio` or `getAspectRatioStyles` on its own, hence it is deprecated. Unless you know there is use case?

For now, I will say "Please refer to the Image component's documentation about the loadingAspectRatio`. Any suggestions are welcome

2022-04-27 12:03 UTC, Vanals commented on site/pages/components/aspect-ratio.mdx
> +# (deprecated) Aspect Ratio
Make sense, thank you Xin

2022-04-27 12:11 UTC, Vanals commented on src/assistive-text/__tests__/assistive-text.stories.tsx
> +      Assistive Text With Logical Paddings and enhancers
Does having both padding and margin make sense for the assistive text?
I wonder if we should have only margin, given the `assistive text` it self has no border. 🤔

2022-04-27 12:13 UTC, Vanals commented on src/assistive-text/__tests__/assistive-text.stories.tsx
> +      Assistive Text With Logical Paddings and enhancers
Shuldn't the padding apply only the the user can add a spacing withing the component it self? for example a button with wants to increase the space between the button text and the button container?
Same question for Audio player

2022-04-27 12:15 UTC, Vanals commented on src/assistive-text/__tests__/assistive-text.stories.tsx
> +      Assistive Text With Logical Paddings and enhancers
What you did in the banner is what I would think as a good application of both padding and margin

2022-04-27 12:21 UTC, Xin00163 commented on src/assistive-text/__tests__/assistive-text.stories.tsx
> +      Assistive Text With Logical Paddings and enhancers
I see what you mean and tbh I kind of agree. For example, checkbox with padding is kind of a weird situation. I had the discussion with @jps . The idea is to keep the logicalProps consistent across all the components. We can't have only margin no padding for one but both margin & padding for the other. At the end of the day, it is up to the user to decide what they want to add to the components and they should consider whether to add padding or margin. 

We can't predict the behaviour of our users, so we probably need to provide the means for them to do so.

2022-04-27 12:35 UTC, Vanals commented on src/assistive-text/__tests__/assistive-text.stories.tsx
> +      Assistive Text With Logical Paddings and enhancers
I see, make sense I guess... . Also natively all the elements can take both padding and margin..then is up to the devs to use them wisely! Maybe was just weird for me to see them applied on storybook. But at least we test them.

2022-04-27 12:41 UTC, Vanals approved these changes

2022-04-27 13:15 UTC, Xin00163 commented on src/assistive-text/__tests__/assistive-text.stories.tsx
> +      Assistive Text With Logical Paddings and enhancers
I am hoping that @pdimova will have time to review this pr tomorrow, so won't merge it yet.

2022-04-28 10:17 UTC, jps commented
Crashing the party very late on this, but don't we need to update the API tables in the docs?

2022-04-28 10:34 UTC, Xin00163 commented
> Crashing the party very late on this, but don't we need to update the API tables in the docs?

Indeed @jps . Totally forgot about that.

2022-04-29 06:53 UTC, pdimova commented on src/utils/logical-properties.ts
> +export const omitLogicalPropsFromOverrides = (overrides: object | undefined) =>
what is the difference between `omitLogicalPropsFromOverrides` and `extractLogicalPropsFromOverrides`?

2022-04-29 06:57 UTC, pdimova commented on src/utils/logical-properties.ts
> +export const extractLogicalPropsFromOverrides = (
Couldn't find any tests for this util function :)

2022-04-29 07:26 UTC, pdimova commented on src/utils/__tests__/logical-properties.test.ts
> +    expect(extractLogicalPropsFromOverrides(undefined)).toEqual({});
not sure about this, why do we need an empty object out of an undefined value?

2022-04-29 07:26 UTC, pdimova commented on src/aspect-ratio/types.ts
> + * @deprecated AspectRatioProps is deprecated and will be removed in the next major release.
we can mention the  Image's `loadingAspectRatio` prop

2022-04-29 07:26 UTC, pdimova commented on src/assistive-text/__tests__/assistive-text.stories.tsx
> +      Assistive Text With Logical Paddings and enhancers
let's have a quick catch up when you both are online

2022-04-29 07:55 UTC, pdimova commented on src/assistive-text/__tests__/assistive-text.stories.tsx
> +        overrides={{marginBlock: 'space050'}}
You can add one more story - both with padding and margin

2022-04-29 07:55 UTC, pdimova commented on src/assistive-text/assistive-text.tsx
> +          overrides={nonLogicalOverrides}
Basically, there is no need to filter out the logical props here since the  `StyledAssistiveText` internal implementation has no logic to apply them. 
But semantically it is good to highlight there props don't belong there

We have plenty of places where we pass unnecessary props inside the overrides object 

Here it is a good place to initiate a props clean-up  :)

2022-04-29 07:55 UTC, pdimova commented on src/assistive-text/__tests__/assistive-text.stories.tsx
> +      Assistive Text With Logical Paddings and enhancers
On second thought, I have mixed feelings about the padding props for this particular component? 

Why do we need padding in general?

> Padding is used to create space around an element's content, inside of any defined borders.
https://www.w3schools.com/css/css_padding.asp

Which is the content inside the `WithEnhancers` container that we'd like to separate from each other? 
I don't see such, though

My understanding of the concept of padding makes me a bit reluctant to add the logical props here.
Let's further discuss it in a huddle

2022-04-29 08:32 UTC, Xin00163 commented on src/utils/logical-properties.ts
> +export const omitLogicalPropsFromOverrides = (overrides: object | undefined) =>
`omitLogicalPropsFromOverrides` will reject the logical props from overrides, while `extractLogicalPropsFromOverrides` will filter out the logical props.

2022-04-29 08:35 UTC, Xin00163 commented on src/utils/__tests__/logical-properties.test.ts
> +    expect(extractLogicalPropsFromOverrides(undefined)).toEqual({});
Because of this `filterObject(overrides || {}, logicalPropsArray as keyof object)`. If it's undefined, it will return `{}`. Otherwise, we will need to check if it's undefined each time we use it.

2022-04-29 08:47 UTC, Xin00163 commented on src/assistive-text/__tests__/assistive-text.stories.tsx
> +        overrides={{marginBlock: 'space050'}}
Let's have a chat about this @pdimova

2022-04-29 10:29 UTC, pdimova commented on src/card/types.ts
>    mediaContainer?: {
what about the spaceInline here?

2022-04-29 10:29 UTC, pdimova commented on src/card/styled.tsx
> +  ${logicalProps('card.teaserContainer', 'teaserContainer')};
do we need margin here?

2022-04-29 10:29 UTC, pdimova commented on src/card/styled.tsx
> +  ${logicalProps('card.actionsContainer', 'actionsContainer')};
same as above? do we need margin? padding here is used only for the inset card

2022-04-29 10:29 UTC, pdimova commented on src/card/card.tsx
> +              overrides={nonLogicalOverrides}
why passing nonLogicalOverrides here? I'm a bit confused why we need this

2022-04-29 13:10 UTC, Xin00163 commented on src/card/card.tsx
> +              overrides={nonLogicalOverrides}
Good point. I will remove the cases where we don't need filter

2022-04-29 13:58 UTC, Xin00163 commented on src/card/styled.tsx
> +  ${logicalProps('card.teaserContainer', 'teaserContainer')};
I only added padding because of `spaceInset` but I tried add margin and it seems OK. I could extend to accept both.

2022-05-02 10:02 UTC, pdimova commented on src/caption/types.ts
> +    spaceStack?: MQ<string>;
This is the gap, can not be deprecated

2022-05-02 11:00 UTC, pdimova submitted a review, later dismissed

2022-05-02 11:00 UTC, pdimova commented on src/radio-button/__tests__/radio-button.stories.tsx
> +              marginBlockEnd: 'space030',
The wrapper GridLayout sets a gap of 16px between the. buttons `rowGap="space040"` Maybe we can remove the Grid for this particular story

2022-05-02 11:00 UTC, pdimova commented on src/card/styled.tsx
>        marginDirection = 'marginRight';
Is this logic still neded?

2022-05-03 08:24 UTC, Xin00163 commented on src/card/styled.tsx
>        marginDirection = 'marginRight';
I think so until `spaceInline` is removed from defaults. I've add a comment to remove it later.

2022-05-03 08:26 UTC, Xin00163 commented on src/caption/types.ts
> +    spaceStack?: MQ<string>;
Good catch

2022-05-03 10:43 UTC, baburay23 approved these changes

2022-05-03 12:53 UTC, pdimova approved these changes
Good job!

2022-05-03 14:42 UTC, merged