chore(PPDSC-2079): update axe-core and fix any errors
newscorp-ghfb/newskit pull request #167
Opened 2022-04-19 11:27 UTC by evgenitsn

PPDSC-2079

**What**

Our `axe-core` and `cypress-axe` versions were not up to date, so I've updated them and cleared all new a11y errors.

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**How to test:**
Run `yarn e2e:build` then `yarn e2e:comps` and check if all tests pass (but that should be handled by circleci either way).

2022-04-19 11:30 UTC, evgenitsn commented on src/scroll/scroll.tsx
> -          aria-orientation={vertical ? 'vertical' : 'horizontal'}
This is not relevant here and the axe-core is throwing errors for not valid attribute. 
The `aria-orientation` should be one of these components (widgets) https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-orientation#description

2022-04-19 11:36 UTC, newskit-engineering commented
You can preview these changes on: 
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2079-update-axe-core-and-fix-any-errors 
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2079-update-axe-core-and-fix-any-errors/storybook

2022-04-20 05:33 UTC, Srinivasan-Ramasamy submitted a review, later dismissed
The code changes look good to me :+1: let's wait others point

2022-04-20 07:01 UTC, mutebg reviewed
👏

2022-04-20 07:02 UTC, mutebg approved these changes

2022-04-20 07:18 UTC, Vanals requested changes

2022-04-20 07:18 UTC, Vanals commented on site/components/__tests__/__snapshots__/site-header.test.tsx.snap
> -                aria-orientation="horizontal"
Why was this attribute removed? 
I wonder if this should be kept and added a role='menu' instead

2022-04-20 07:23 UTC, Vanals requested changes

2022-04-20 07:23 UTC, Vanals commented on src/scroll/scroll.tsx
> -          aria-orientation={vertical ? 'vertical' : 'horizontal'}
Rather than remove it, should we instead add the `scrollbar` role? 
Seems like that's what the component is

2022-04-20 07:23 UTC, Vanals commented on src/slider/slider.tsx
> -        aria-orientation={vertical ? 'vertical' : 'horizontal'}
have they been removed for the same reason mentioned above? I wonder if the same can be done.

2022-04-20 10:32 UTC, evgenitsn commented on src/scroll/scroll.tsx
> -          aria-orientation={vertical ? 'vertical' : 'horizontal'}
Adding a `role='scrollbar'` then throws another error for not having `aria-valuenow` attribute. 
<img width="379" alt="image" src="https://user-images.githubusercontent.com/7677924/164212313-9b8ab8bc-a938-472e-849c-8afd95b3fb42.png">

In this article are described all required attributes for a scrollbar https://www.digitala11y.com/scrollbar-role/
I am not sure if the intent of a `scrollbar` is the same as our use case for the `scroll` component. 
Also the children of the `scroll` component are dynamic (up to the consumer) and they can be a single child with many children inside (like a Scroll with Stack inside) or multiple children (like a set of images). These examples are from storybook. So we can't be sure if the direct children of the Scroll would be a single element or many elements.

2022-04-20 10:33 UTC, evgenitsn commented on src/slider/slider.tsx
> -        aria-orientation={vertical ? 'vertical' : 'horizontal'}
So these have been moved from the track to the thumb element of the same component. 
axe-dev is showing this error and after a research I found out that these aria attributes should be on the thumb so I moved them and the errors are now gone.

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/7677924/164207700-5cc10934-2e6b-4fda-8368-b1996b6a6d17.png">

2022-04-20 13:00 UTC, Vanals commented on src/scroll/scroll.tsx
> -          aria-orientation={vertical ? 'vertical' : 'horizontal'}
uhm! Ok! thanks! Let see if we get any feedback in future!

2022-04-20 13:01 UTC, Vanals commented on src/slider/slider.tsx
> -        aria-orientation={vertical ? 'vertical' : 'horizontal'}
Make sense! thanks! I am just bit confused because if I go in storybook prod or dev I can see these values are already in the thumb?
Also, does the screen reader reads ok after this change? Not sure what scenario  was affected if any specificly

2022-04-20 13:08 UTC, Vanals approved these changes

2022-04-20 15:50 UTC, Srinivasan-Ramasamy approved these changes

2022-04-21 04:09 UTC, mutebg approved these changes

2022-04-21 06:20 UTC, merged