Feat/ppdsc 2112 audio player v2 volume control
newscorp-ghfb/newskit pull request #208
Opened 2022-05-24 14:28 UTC by Vanals

PPDSC-2112

**What**

Created VolumeControl component inside AudioPlayerComposable folder.
Implemented the same functionality we have in the old Audio Player
Implemented new props: InitialVolume, Collapsed
Implemented `length` in default.ts in `track` object.

Make tests pass,
Vertical scenario 

**I have done:**
- [x] Written unit tests against changes
- [x] Written functional tests against the component and/or NewsKit site
- N/A Updated relevant documentation

**I have tested manually:**
- [x] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [x] The screen reader reads and flows through the elements as expected.
- [x] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-05-24 14:34 UTC, newskit-engineering commented
You can preview these changes on: 
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2112-audio-player-v2-volume-control 
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2112-audio-player-v2-volume-control/storybook

2022-06-01 16:22 UTC, mstuartf commented on src/audio-player-composable/components/volume-control/utils.ts
> +  const sliderIndicatorTrackStylePreset = getVolumeControlToken(
Should this just be `sliderIndicatorStylePreset` or `volumentControlIndicatorStylePreset`? Some of the naming for the indicator and the thumb is a bit inconsistent.

2022-06-01 16:22 UTC, mstuartf commented on src/audio-player-composable/components/volume-control/volume-control.tsx
> +    setUnMutedVolume(volume);
Should this be done in a `useEffect` rather than an if statement?

2022-06-01 16:22 UTC, mstuartf commented on src/audio-player-composable/components/volume-control/volume-control.tsx
> +  } = getVolumeControlProps!(props);
Why are these tokens calculated here, rather than following the normal pattern of using the helper functions inside styled components - is it to avoid making edits to the components used internally?

2022-06-01 16:22 UTC, mstuartf commented on src/audio-player-composable/components/volume-control/types.ts
> +  onChange: (volume: number) => void;
I think perhaps too much state is passed to this button. It should just need a boolean to know which icon to show, and an `onClick` callback. The parent should then decide what to do `onClick`. It seems strange to pass `unMuted` volume down to the button when it is not actually used by the component, it is only passed into the callback if `volume` is 0. 

What do you think?

2022-06-03 11:31 UTC, mutebg requested changes

2022-06-03 11:31 UTC, mutebg commented on src/audio-player-composable/components/volume-control/volume-control.tsx
> +  } = getVolumeControlProps!(props);
I think that can be achieved in an easier way as we do for other components: 
```ts
const sliderOverrides =  {
    ...deepMerge(
      mergeBreakpointObject(Object.keys(theme.breakpoints) as BreakpointKeys[]),
      theme.componentDefaults.audioPlayerVolumeControl.slider,
      filterOutFalsyProperties(overrides?.slider),
    ),
  };
```
and pass this down to the slider `<Slider overrides={sliderOverrides} />`
you can do the same for the mute button

2022-06-03 11:31 UTC, mutebg commented on src/audio-player-composable/components/volume-control/volume-control.tsx
> +  const volumeSliderInstructionId = useReactKeys(1)[0];
```suggestion
  const [volumeSliderInstructionId] = useReactKeys(1);
```

2022-06-03 11:31 UTC, mutebg commented on src/audio-player-composable/components/volume-control/types.ts
> +  muteKeyboardShortcuts?: string[] | string;
that adds 1 more naming convention for the audio player :D 
I would make it only `keyboardShortcuts`  so is consistent with other sub-components or 
```
keyboardShortcuts: {
   mute: 'string'
}
```
so that is consistent with AudioPlayerComposable

2022-06-03 11:31 UTC, mutebg commented on src/audio-player-composable/types.ts
> +    initialVolume: 0 | 0.1 | 0.2 | 0.3 | 0.4 | 0.5 | 0.6 | 0.7 | 0.8 | 0.9 | 1;
Why a volume is a number and initialVolume one union type?

2022-06-03 11:31 UTC, mutebg commented on src/audio-player-composable/audio-player-composable.tsx
> +    }),
```suggestion
  (volumeProps: AudioPlayerVolumeControlProps) => ({
      onChange: onChangeVolumeSlider,
      volume,
      initialVolume,
      ...volumeProps,
    }),
```

2022-06-06 08:11 UTC, Vanals commented on src/audio-player-composable/components/volume-control/utils.ts
> +  const sliderIndicatorTrackStylePreset = getVolumeControlToken(
It needs to specify the "track" in the name as that is what the preset is for! But if you have any proposal for the naming please share the syntax 👍 . The one you suggested I guess must include track.

```
  const sliderTrackStylePreset = getVolumeControlToken(
    'slider.track',
    'stylePreset',
  );
  const trackSize = getVolumeControlToken('slider.track', 'size');
  const sliderIndicatorTrackStylePreset = getVolumeControlToken(
    'slider.indicator',
    'stylePreset',
  );
  const sliderThumbStylePreset = getVolumeControlToken(
    'slider.thumb',
    'stylePreset',
  );
  const thumbSize = getVolumeControlToken('slider.thumb', 'size');
  const volumeControlButtonStylePreset = getVolumeControlToken(
    'button',
    'stylePreset',
  );
  const iconSize = getVolumeControlToken('button', 'iconSize');
  const buttonSize = getVolumeControlToken('button', 'size');
  ```
  
  This is what we have. They might sound weird because the come from the `volumeControl` component already existing

2022-06-06 08:13 UTC, Vanals commented on src/audio-player-composable/components/volume-control/volume-control.tsx
> +    setUnMutedVolume(volume);
For how the audioPlayerComposable works, it is going to re render everytime something changes anyway 👀 . So the UseEffect kind of loses it's pro here I belive

2022-06-06 10:11 UTC, Vanals commented on src/audio-player-composable/components/volume-control/utils.ts
> +  const sliderIndicatorTrackStylePreset = getVolumeControlToken(
@mstuartf  gonna be removed with the approach suggested by Stoyan  in https://github.com/newscorp-ghfb/newskit/pull/208#discussion_r888848898

2022-06-06 10:12 UTC, Vanals commented on src/audio-player-composable/components/volume-control/volume-control.tsx
> +  } = getVolumeControlProps!(props);
@mstuartf  not sure what you mean  on this 🤔 . I checked with stoyan but he meant something else in his comment here (the overrides).

This are the props coming from the getter! I am just restructuring them for visibility, nothing else 🤔 . See  time label for example. Let me know 👍

2022-06-06 10:13 UTC, Vanals commented on src/audio-player-composable/components/volume-control/types.ts
> +  onChange: (volume: number) => void;
Hey @mstuartf ! That prop is needed for logic specifically belonging to the mute button! I guess we could pass less props but then we should move logic specifically belonging to the mute button 1 level up. I believe the logic specifically belonging to the muteButton should stay there 🤔 . For splitting the responsabilities

2022-06-06 10:14 UTC, Vanals commented on src/audio-player-composable/audio-player-composable.tsx
> +  const [volume, setVolume] = useState(0);
as discussed is not needed 👍

2022-06-06 10:46 UTC, mutebg commented on src/audio-player-composable/components/volume-control/types.ts
> +  onChange: (volume: number) => void;
I agree that keeping the button and mute logic in the same file makes it easier to read and maintain

2022-06-06 13:06 UTC, Vanals commented on src/audio-player-composable/components/volume-control/volume-control.tsx
> +    setUnMutedVolume(volume);
yeo, Done 👍

2022-06-06 13:06 UTC, Vanals commented on src/audio-player-composable/components/volume-control/defaults.ts
> +      size: 'small',
done 👍

2022-06-06 13:06 UTC, Vanals commented on src/audio-player-composable/components/volume-control/types.ts
> +  muteKeyboardShortcuts?: string[] | string;
Done 👍

2022-06-09 05:30 UTC, mutebg commented on src/audio-player-composable/components/volume-control/types.ts
> +  keyboardShortcuts?: {muteButton: string | string[]};
what about calling this just mute
```suggestion
  keyboardShortcuts?: {mute: string | string[]};
```

2022-06-09 05:30 UTC, mutebg commented on src/audio-player-composable/components/volume-control/utils.ts
> +
I believe you also can use the same deepMerge for the button and these styles
```js
const buttonOverrides = {
  ....deepMerge(
      mergeBreakpointObject(Object.keys(theme.breakpoints) as BreakpointKeys[]),
      theme.componentDefaults.audioPlayerVolumeControl.button,
      filterOutFalsyProperties(overrides?.button),
    ),
};
```

2022-06-09 08:07 UTC, mutebg commented on src/audio-player-composable/components/volume-control/types.ts
> +  keyboardShortcuts?: {muteButton: string | string[]};
`muteToggle` ?

2022-06-10 11:36 UTC, Vanals commented on src/audio-player-composable/components/volume-control/utils.ts
> +
Done

2022-06-10 11:36 UTC, Vanals commented on src/audio-player-composable/components/volume-control/types.ts
> +  keyboardShortcuts?: {muteButton: string | string[]};
Done

2022-06-10 13:28 UTC, mutebg submitted a review, later dismissed

2022-06-14 05:31 UTC, mutebg approved these changes

2022-06-15 12:33 UTC, mutebg approved these changes

2022-06-16 15:37 UTC, mstuartf approved these changes

2022-06-17 09:05 UTC, merged