feat(PPDSC-2118): tooltip pointer
newscorp-ghfb/newskit pull request #217
Opened 2022-05-31 16:43 UTC by mstuartf

[PPDSC-2118](https://nidigitalsolutions.jira.com/browse/PPDSC-2118)

**What**

1. Background - v1 tooltip did not have a pointer arrow or ability to adjust distance
2. What did you do - added optional pointer element to tooltip and ability to control distance

**I have done:**
- [x] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

2022-05-31 16:50 UTC, newskit-engineering commented
You can preview these changes on: 
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2118-tooltip-pointer 
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2118-tooltip-pointer/storybook

2022-06-03 11:44 UTC, mutebg requested changes

2022-06-03 11:44 UTC, mutebg commented on src/tooltip/defaults.ts
> +  tooltipPanel: {
I believe we should use nested objects
```
export default {
  tooltip: {
    zIndex: 80,
    stylePreset: 'tooltip',
    distance: 'space020',
    pointer: {
      size: 'sizing010',
    },
    panel: {
      stylePreset: 'tooltipPanel',
      typographyPreset: 'utilityLabel010',
      paddingBlock: 'spaceInset020',
      paddingInline: 'spaceInset020',
    },
  },
};
```

2022-06-03 11:44 UTC, mutebg commented on src/tooltip/styled.tsx
> +  ${getStylePreset('tooltipPanel', 'panel')};
getStylePreset is used 2 times with different paths
also if that's the panel can we rename the component to StyledPanel

2022-06-03 11:44 UTC, mutebg commented on src/tooltip/tooltip.tsx
> +  const {distance} = getResponsiveSpace(
according to the types, this can be MQ<string>, if you want to use this function better change the type

2022-06-03 11:44 UTC, mutebg commented on src/tooltip/tooltip.tsx
> +  return parseInt(distance.replace('px', ''), 10);
what if the value is not `px`?

2022-06-06 10:03 UTC, mstuartf commented on src/tooltip/tooltip.tsx
> +  const {distance} = getResponsiveSpace(
Oh yes, good point. 

Is it better to change the type or to handle MQs and follow the spec? It seems likely that users might want to set distance conditional on screen size. 

If we do want to handle MQs, we'd need to calculate the offset inside the `getResponsiveSpace` callback using logic like this: https://github.com/floating-ui/floating-ui/blob/master/packages/core/src/middleware/offset.ts#L32, then update the `left` and `top` values for the div. Annoyingly I don't think we can just use this function from the lib because it is async. It's not too complicated but it would mean duplicating some of the library logic on our side, which I don't love. What do you think?

2022-06-06 10:04 UTC, mstuartf commented on src/tooltip/styled.tsx
> +  ${getStylePreset('tooltipPanel', 'panel')};
It's called twice because the panel has its own styling (border radius, color) and the tooltip styling that it shares with the pointer (background color). Is there a better way to do this?

2022-06-06 12:00 UTC, mutebg commented on src/tooltip/styled.tsx
> +  ${getStylePreset('tooltipPanel', 'panel')};
I understand why is like that but still seems weird to me, there can be conflicts, like if both have borders? the panel ones will always override the tooltip ones.  Maybe we can do something like this ( as the designer envisioned hat )
```
<StyledTooltip>
  <StyledPanel />
  <StyledPointer />
</StyledTooltip>
```
![image](https://user-images.githubusercontent.com/3543332/172156283-5b5f51e0-72d1-45af-9917-35140df4a1dc.png)

2022-06-06 12:21 UTC, mutebg commented on src/tooltip/tooltip.tsx
> +  const {distance} = getResponsiveSpace(
What do you think about setting an offset via padding on the tooltip container? something like this https://codepen.io/mutebg/pen/JjpBwqv that case we don't use floating UI functions we do it by ourselves, which will allow also use non-px values. I am not sure if that's gonna work just had that idea

2022-06-06 12:36 UTC, mstuartf commented on src/tooltip/styled.tsx
> +  ${getStylePreset('tooltipPanel', 'panel')};
I agree that having a containing tooltip element makes sense. Happy to implement that.

2022-06-06 12:36 UTC, mstuartf commented on src/tooltip/tooltip.tsx
> +  const {distance} = getResponsiveSpace(
We'd still need to duplicate the library logic (to know which to side to apply the padding). But I don't think there's any way round that.

2022-06-06 12:41 UTC, mutebg commented on src/tooltip/tooltip.tsx
> +  const {distance} = getResponsiveSpace(
my idea is not to use the offset function at all, maybe we can catch up on that tomorrow, I might need to better understanding of how it works

2022-06-06 13:22 UTC, mstuartf commented on src/tooltip/styled.tsx
> +  ${getStylePreset('tooltipPanel', 'panel')};
Actually this will not solve the problem. If the background color is applied to the tooltip element, the pointer (which is positioned absolutely to sit outside the container) does not inherit this. Also the border radius of the panel would need to be applied to the tooltip element, rather than to the panel.

The options are:
* Call `getStylePreset` twice to apply shared and specific styling.
* Set background color twice (once for the panel and once for the pointer. 

(But I do still think it makes sense to have a separate container element.)

2022-06-06 13:38 UTC, mstuartf commented on src/tooltip/tooltip.tsx
> +  const {distance} = getResponsiveSpace(
Yeah, I just mean that we will be re-implementing some logic that the library already handles. But I think that it's unavoidable.

2022-06-06 13:49 UTC, mstuartf commented on src/tooltip/tooltip.tsx
> +  const {distance} = getResponsiveSpace(
<img width="210" alt="Screenshot 2022-06-06 at 14 48 11" src="https://user-images.githubusercontent.com/26839368/172173680-c8f36943-6423-4cac-b7a8-7c2a46a58696.png">

Using padding doesn't work with how the lib implements the points (relative to the tooltip element).

2022-06-06 14:51 UTC, mstuartf commented on src/tooltip/tooltip.tsx
> +  return parseInt(distance.replace('px', ''), 10);
Good point. Handled using `calc`.

2022-06-06 15:31 UTC, mstuartf commented on src/tooltip/styled.tsx
> +  ${getStylePreset('tooltipPanel', 'panel')};
For now I've reverted to setting background color separately for the panel and the pointer. Let me know what you think.

2022-06-06 15:32 UTC, mstuartf commented on src/tooltip/tooltip.tsx
> +  const {distance} = getResponsiveSpace(
For now I'm updating the `top` / `left` values in the styled component. This supports non-px values and MQs. Let me know what you think.

2022-06-07 05:26 UTC, mutebg commented on src/tooltip/tooltip.tsx
> +  const {distance} = getResponsiveSpace(
IMO looks very good.

2022-06-07 05:28 UTC, mutebg commented on src/tooltip/styled.tsx
> +  ${getStylePreset('tooltipPanel', 'panel')};
I personally like it this way

2022-06-07 05:45 UTC, mutebg reviewed
just 1 small comment, well done 👏

2022-06-07 05:45 UTC, mutebg commented on src/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap
> +    y="0"
can you remove these attributes from the HTML, you can rename your prop to $x and $y so that they don't end up in the HTML or use [shouldForwardProp](https://emotion.sh/docs/styled#customizing-prop-forwarding)

2022-06-07 05:45 UTC, mutebg commented on src/tooltip/tooltip.tsx
>    title,
I know this is not from your ticket but do you know why is called `title`, isn't it better to be named `content` or `render`? 
@Xin00163

2022-06-07 08:04 UTC, Xin00163 commented on src/tooltip/tooltip.tsx
>    title,
This is the name Mike had in design. I didn't feel too strongly about it but if you all think `content` is better, we can change it.

2022-06-07 08:10 UTC, mstuartf commented on src/tooltip/tooltip.tsx
>    title,
Would this count as a breaking change if the first version of the tooltip has been released? Same for the changes to overrides actually.

2022-06-07 08:21 UTC, mstuartf commented on src/tooltip/tooltip.tsx
>    title,
OK cool, done. All changes made.

2022-06-07 08:39 UTC, mutebg submitted a review, later dismissed

2022-06-07 10:25 UTC, Xin00163 reviewed
Could we add the `aria-hidden` attribute to tooltip like https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA1? This is something I missed in the last pr. When scanning through with screenreader, the content of the tooltip is read twice. By adding this, we can avoid redundancy. Happy to have a chat about this.

2022-06-07 13:53 UTC, mstuartf commented on src/tooltip/__tests__/tooltip.test.tsx
> +        showPointer: true,
Yes, that makes sense.

2022-06-07 14:58 UTC, mstuartf commented on src/tooltip/utils.ts
> +export function calculateInset(
👍

2022-06-08 05:24 UTC, mutebg approved these changes

2022-06-08 08:01 UTC, Xin00163 approved these changes

2022-06-08 09:51 UTC, merged