fix(PPDSC-2199): docs-ppdse-2199-fixed
newscorp-ghfb/newskit pull request #230
Opened 2022-06-13 11:09 UTC by baburay23

PPDSC-XXXX

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-06-13 11:17 UTC, newskit-engineering commented
You can preview these changes on: 
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2199-drawer-correct-state 
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2199-drawer-correct-state/storybook

2022-06-21 05:42 UTC, mutebg requested changes

2022-06-21 05:42 UTC, mutebg commented on src/drawer/utils.ts
> +  let prefixClassName = '';
technically this is a `suffix`

2022-06-21 05:42 UTC, mutebg commented on src/drawer/utils.ts
> +};
Not sure if we need to have this function, for now, we only have 2 components and its easy but every time we need to use the function we need to add another statement to that if/else.
I personally wound go with `setCorrectClassName(prefix, state) => ...` and use it like `setCorrectClassName('nk-drawer', state)`

2022-06-21 05:42 UTC, mutebg commented on src/modal/modal.tsx
> +import {setCorrectClassName} from '../drawer/utils';
maybe is better to move this function to `src/utils/` so it's more obvious that is a shared one.

2022-06-21 05:42 UTC, mutebg commented on src/modal/__tests__/modal.stories.tsx
> +//     const [themeMode, setThemeMode] = React.useState('light');
just cleanup this one, or un-comment it so people can test it.

2022-06-21 05:42 UTC, mutebg commented on src/drawer/utils.ts
> +export const setCorrectClassName = (
```suggestion
export const getTransitionClassName = (
```

2022-06-21 07:58 UTC, baburay23 commented on src/drawer/utils.ts
> +};
my bad i went a bit over board!

2022-06-21 08:28 UTC, baburay23 commented on src/modal/__tests__/modal.stories.tsx
> +//     const [themeMode, setThemeMode] = React.useState('light');
i have removed it i thought if people would like to test they can use the example in the tickeT?

2022-06-21 08:48 UTC, mstuartf requested changes
If I'm understanding correctly, the bug was triggered when the Theme changed. Can we add a test that covers this case? I.e. a test that changes the Theme when a Drawer is open, and then asserts that the Drawer is still open?

2022-06-21 13:42 UTC, baburay23 commented
> 



> If I'm understanding correctly, the bug was triggered when the Theme changed. Can we add a test that covers this case? I.e. a test that changes the Theme when a Drawer is open, and then asserts that the Drawer is still open?

@mstuartf yes thats the case. Thanks for pointing it out i have written a test that clicks on the toggle theme button inside the drawer and i make sure the drawer has the correct transition class added to it `nk-drawer-enter-done` this confirms the drawer remains open after the theme is toggled. without the className the drawer would close

2022-06-21 13:48 UTC, mstuartf submitted a review, later dismissed

2022-06-21 14:13 UTC, baburay23 commented on src/drawer/__tests__/drawer.test.tsx
> +    expect(getByTestId('drawer')).toBeInTheDocument();
yes you are right sorry, i will remove and just use `tohaveClass` as this tests its still open

2022-06-22 05:48 UTC, mutebg approved these changes

2022-06-22 06:16 UTC, Srinivasan-Ramasamy approved these changes

2022-06-22 08:06 UTC, merged