feat(PPDSC-2218): added Scroll storybook scenario
newscorp-ghfb/newskit pull request #248
Opened 2022-06-30 14:49 UTC by agagotowiec

PPDSC-2218

**What**

1. Background - why this is needed
Missing scenario in the scroll component storybook showcasing how users can scroll inside the container using tab key.

2. What did you do
Added a scenario to the scroll component storybook that allow the user to scroll inside of the container using the tab key.

3. What does the reviewers should expect
A scenario where focus moves to first interactive element inside the container and then through the other interactive elements.

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [x] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [x] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**After:**
![Screenshot 2022-07-05 at 09 17 49](https://user-images.githubusercontent.com/92727370/177282991-32fd0b28-d063-4748-ac6e-3a400da3edb5.png)

**Who should review this PR:**

**How to test:**
Please check scenario 'scroll-inside-the-container-with-tab-key' in the scroll component storybook

2022-07-01 09:45 UTC, evgenitsn approved these changes

2022-07-01 09:45 UTC, evgenitsn submitted a review, later dismissed
Looks good 👍

2022-07-01 10:01 UTC, mutebg requested changes

2022-07-05 08:46 UTC, agagotowiec commented on src/scroll/__tests__/scroll.stories.tsx
> +);
Done

2022-07-05 09:47 UTC, mutebg approved these changes

2022-07-06 10:37 UTC, merged