Feat/ppdsc 2253 storybook scenarios and UL default updates
newscorp-ghfb/newskit pull request #295
Opened 2022-07-18 12:15 UTC by Vanals

PPDSC-2253

**What**

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-07-18 12:25 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2253-storybook-scenarios-updates
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2253-storybook-scenarios-updates/storybook

2022-07-25 08:20 UTC, mutebg requested changes

2022-07-25 08:20 UTC, mutebg commented on lib/codemod/src/transforms/__tests__/remove-redundant-marker-ul/actual.js
> +`;
this can be just as JSX not need for quotes around, same as expected

2022-07-25 08:20 UTC, mutebg commented on lib/codemod/src/utils/add-prop.js
> +        doesListItemMarkerExist = true;
```suggestion
        doesPropExist = true;
```

2022-07-25 08:20 UTC, mutebg commented on lib/codemod/src/utils/add-prop.js
> +module.exports = function addProp(
```suggestion
module.exports = function addNullPropValueWhenNotExist(
```

2022-07-25 08:20 UTC, mutebg commented on src/unordered-list/unordered-list.tsx
> +                {ListItemMarker ? (
Actually, you might need to add a condition for `null` so when is null you should not render anything. 
Right now that's not supported, also need to update types to support null

2022-08-02 08:27 UTC, Vanals commented on lib/codemod/src/transforms/__tests__/remove-redundant-marker-ul/actual.js
> +`;
done 👍

2022-08-02 08:27 UTC, Vanals commented on src/unordered-list/unordered-list.tsx
> +              </StyledMarkerBlock>
Done 👍

2022-08-02 08:27 UTC, Vanals commented on lib/codemod/src/utils/add-prop.js
> +        doesListItemMarkerExist = true;
Done 👍

2022-08-02 08:29 UTC, Vanals commented on lib/codemod/src/utils/add-prop.js
> +module.exports = function addProp(
The value can be anything with this function! And I thing is a good thing, so it is flexible. This function allows you to add a props and it's value.  Doesn't have to be always null and can take any value

2022-08-02 08:36 UTC, Vanals commented on src/unordered-list/unordered-list.tsx
> +                {ListItemMarker ? (
I have written it like that

```            
{ListItemMarker === null ? null :
                <ListItemMarker
                  overrides={{
                    size: markerSizeToken,
                    stylePreset: markerStylePresetToken,
                  }}
                />
              }
```

I could use `&&` but I think is more explicit on what we are trying to support here and why.

2022-08-03 09:26 UTC, baburay23 commented on .gitignore
> +.eslintcache
looks good am ready to approve! but i wanted to ask what is the difference between this slight change? sorry i cant find an explanation of it for a gitignore file

2022-08-03 09:26 UTC, baburay23 submitted a review, later dismissed

2022-08-04 12:10 UTC, Vanals commented on .gitignore
> +.eslintcache
I did it before going on holiday so hopefully I remember correctly, but basically, it wasn't being ignored! 

Probably is not a valid syntax to have a slash at the beginning

2022-08-08 10:58 UTC, mstuartf commented on lib/codemod/src/transforms/remove-redundant-marker-ul.js
> +module.exports = function (file) {
Should this and the update mod be listed in `cli.js`?

```
// Codemods names and descriptions are defined below.
// Users can select one of these to run from the CLI
const TRANSFORMS = {
  'update-token': 'Update newskit tokens from v5 to v6',
  'emotion-icons': 'Update newskit icons to use @emotion-icons',
};
```

2022-08-08 10:58 UTC, mstuartf commented on lib/codemod/src/transforms/remove-redundant-marker-ul.js
> +module.exports = function (file) {
Also in the README with a description of what it does:
```
## Included scripts
The list includes these transformers

- [`emotion-icons`](#emotion-icons)
```

2022-08-09 09:52 UTC, mutebg submitted a review, later dismissed

2022-08-09 12:34 UTC, Vanals commented on lib/codemod/src/transforms/remove-redundant-marker-ul.js
> +module.exports = function (file) {
Done! :)

2022-08-09 13:04 UTC, mstuartf approved these changes

2022-08-10 06:02 UTC, mutebg approved these changes

2022-08-10 07:37 UTC, mstuartf approved these changes

2022-08-10 08:14 UTC, merged