feat(PPDSC-2242): update to node 18
newscorp-ghfb/newskit pull request #301
Opened 2022-07-19 15:45 UTC by tbradbury

PPDSC-XXXX

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-07-26 14:23 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2242-react-18
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2242-react-18/storybook

2022-08-10 05:50 UTC, mutebg requested changes

2022-08-10 05:50 UTC, mutebg commented on src/select/select.tsx
> +      (event: {selectedItem: {props: {value: string}}}) => {
```suggestion
      (event: UseSelectStateChange<React.ReactNode>) => {
```

2022-08-10 05:50 UTC, mutebg commented on src/select/select.tsx
> +      onSelectedItemChange: () => onInputChange,
that's not needed once the `onInputChange` type is fixed

2022-08-10 05:50 UTC, mutebg commented on src/select/types.ts
> +  panelLabel?: string;
Why these are needed?

2022-08-10 05:50 UTC, mutebg commented on src/text-input/text-input.tsx
> +              <>{errorText || assistiveText}</>
remove `<>`

2022-08-10 05:50 UTC, mutebg commented on src/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap
> +  top: -8px;
wondering why these snapshots changed

2022-08-10 05:50 UTC, mutebg commented on src/unordered-list/types.ts
> +  children?: React.ReactNode;
```suggestion
  children: Array<React.ReactNode>
```

2022-08-10 05:50 UTC, mutebg commented on src/unordered-list/styled.ts
> +`;
same StyledTextBlock

2022-08-10 05:50 UTC, mutebg commented on src/unordered-list/unordered-list.tsx
> +                as="span"
same `span`

2022-08-10 05:50 UTC, mutebg commented on src/popover/__tests__/__snapshots__/popover.test.tsx.snap
> +  left: -12px;
why these changed

2022-08-10 05:50 UTC, mutebg commented on src/select/__tests__/select.test.tsx
> +        panelLabel,
These seems already part of the `commonProps`

2022-08-10 08:39 UTC, mstuartf commented on site/components/base-card/base-card.tsx
> +          as="span"
I think this is to get rid of the `validateDOMNesting` warnings but I don't think this is anything to do with React 18. I'm running main locally and on the `/theme/presets/typography-presets/` page I get these warnings already.

2022-08-10 08:40 UTC, mstuartf commented on site/components/base-card/base-card.tsx
> +          as="span"
I will revert these changes and see if doing so causes any new errors or warnings. But I do think we should create a ticket to look into all the warnings you get when running the site locally. There are loads and it makes understanding what is happening very difficult.

2022-08-15 07:57 UTC, mstuartf commented on site/components/base-card/base-card.tsx
> +          as="span"
Reverted

2022-08-15 08:00 UTC, mstuartf commented on site/components/base-card/types.ts
> +  children?: React.ReactNode;
tidied

2022-08-15 08:04 UTC, mstuartf commented on site/components/border-card/border-card.tsx
> +  children?: React.ReactNode;
It looks like children were being incorrectly passed in `table/column-renderer.tsx`. I have corrected this and removed the unused prop.

2022-08-15 08:41 UTC, mstuartf commented on site/components/content-structure/content-base.tsx
> +          <StyledTextBlock as="span" {...descriptionOverrides}>
removed

2022-08-15 09:38 UTC, mstuartf commented on site/components/table/column-renderer.tsx
> +            <>{v}</>
reverted

2022-08-15 14:55 UTC, mstuartf commented on src/audio-player-composable/components/seek-bar/seek-bar.tsx
> +      props: any; // react-range does not export IRenderTrackParams
done

2022-08-15 14:57 UTC, mstuartf commented on src/audio-player/audio-player.tsx
> +      props: any; // react-range does not export IRenderTrackParams
done

2022-08-15 15:16 UTC, mstuartf commented on src/base-switch/base-switch.tsx
> +      (event: {target: {checked: boolean}}) => {
updated

2022-08-15 15:35 UTC, mstuartf commented on src/form/form-entry.tsx
> +    error: errorText as string,
added

2022-08-16 08:02 UTC, mstuartf commented on src/grid-layout/grid-layout.tsx
> +        <>{isFunctionWithAreas ? children(Areas) : children}</>
updated

2022-08-16 09:15 UTC, mstuartf commented on src/ordered-list/types.ts
> +  children: React.ReactNode;
So it's not a breaking change I will make this `children?: React.ReactNode[] | React.ReactNode`. Same for `UnorderedList`.

The logic won't need to change as `React.Children` handles both:

> If children is an array it will be traversed and the function will be called for each child in the array. If children is a Fragment it will be treated as a single child and not traversed.

But if we limit it to `React.ReactNode` then anyone not currently passing an array will have to make changes (we have examples of this in our own codebase).

2022-08-16 09:44 UTC, mstuartf commented on src/popover/__tests__/__snapshots__/popover.test.tsx.snap
> +  left: -12px;
I think this is just because the async styling is now being applied in time for the snapshot comparison when for some reason it wasn't before. I don't really understand but this test hasn't changed at all. `-12px` seems to be the value when the `Popover` has default placement.

2022-08-16 09:44 UTC, mstuartf commented on src/popover/popover.tsx
> +              <>{content}</>
removed

2022-08-16 10:37 UTC, mstuartf commented on src/select/select.tsx
> +      onSelectedItemChange: () => onInputChange,
resolved

2022-08-16 10:37 UTC, mstuartf commented on src/select/select.tsx
> +      (event: {selectedItem: {props: {value: string}}}) => {
resolved

2022-08-16 13:34 UTC, mstuartf commented on src/select/types.ts
> +  panelLabel?: string;
I think this was to control the ids generated by `downshift` and make the tests less brittle. I've removed this and mocked the id generation in the module during tests so the IDs are always the same (similar to popover / tooltip).

2022-08-16 14:47 UTC, mstuartf commented on src/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap
> +  top: -8px;
same as popover I think

2022-08-17 06:40 UTC, mutebg commented on src/audio-player-composable/__tests__/audio-player-composable.test.tsx
> +}));
Do you think it is useful and possible to mock that at the global level? 
we have `getSSRId` util which we mock in `test-framework-setup.ts` so all components which use it will benefit from that

2022-08-17 07:44 UTC, mstuartf commented on src/audio-player-composable/__tests__/audio-player-composable.test.tsx
> +}));
Yeah. I've got a todo to create a ticket to mock IDs created by all third party libs in tests (e.g. `downshift` is another). Doing this globally is probably the best way.

2022-08-26 09:31 UTC, mutebg approved these changes

2022-08-26 09:45 UTC, Vanals approved these changes

2022-08-26 10:31 UTC, Srinivasan-Ramasamy approved these changes

2022-08-26 11:14 UTC, mutebg approved these changes

2022-08-26 11:14 UTC, merged