docs(PPDSC-2204): release notes
newscorp-ghfb/newskit pull request #319
Opened 2022-07-29 08:32 UTC by mstuartf

[PPDSC-2204](https://nidigitalsolutions.jira.com/browse/PPDSC-2204)

**What**

1. Background - provide info on our releases
2. What did you do - added a release notes page
3. What does the reviewers should expect - release notes page matching spec

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-07-29 14:31 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2204-release-notes
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2204-release-notes/storybook

2022-08-08 11:47 UTC, baburay23 commented on site/utils/release-notes/functions.ts
> +              ? 'major'
does this todo still need to be here?

2022-08-08 13:09 UTC, Vanals requested changes

2022-08-08 13:09 UTC, Vanals commented on site/pages/about/release-notes.tsx
> +  const [lastRelease, ...previousReleases] = fullReleases;
Judging by the release notes: https://nidigitalsolutions.jira.com/wiki/spaces/NPP/pages/1334083669/Engineering+release+process
I think the latest note might not be showed correctly 🤔 . At the point, we are triggering the release, and everything gets built, in the GitHub `release` section we have a "draft note" with a title and a tag such as `trigger-release@x.x.x`. And unless we want to run to GitHub before the build happens and change the title and tag with the right ones, maybe the release page should not be static? if possible?

2022-08-08 13:13 UTC, mstuartf commented on site/utils/release-notes/functions.ts
> +              ? 'major'
Ah yes, I added that so there was a `major` release for design review. Will remove.

2022-08-08 13:18 UTC, mstuartf commented on site/pages/about/release-notes.tsx
> +  const [lastRelease, ...previousReleases] = fullReleases;
Not sure I follow. What do you mean by 'immediately change the notes to github'?

2022-08-08 14:59 UTC, mstuartf commented on site/pages/about/release-notes.tsx
> +  const [lastRelease, ...previousReleases] = fullReleases;
Added a `updateFinalReleaseInfo` function to perform the update to the name, tag_name and compare link when required.

2022-08-09 08:22 UTC, baburay23 approved these changes

2022-08-09 08:46 UTC, Vanals approved these changes

2022-08-09 09:52 UTC, merged