chore(PPDSC-2329): chore-ppdse-2329-added scripts
newscorp-ghfb/newskit pull request #330
Opened 2022-08-08 15:13 UTC by baburay23

PPDSC-XXXX

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-08-08 15:22 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2329-codemod-link-component
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2329-codemod-link-component/storybook

2022-08-11 12:27 UTC, baburay23 commented on lib/codemod/src/transforms/update-linkinline.js
> +const removeLink = (j, root, list) => {
just wanted to mention I tried to export` getNewskitImports() `and `removeLink()` from the utils file so i it can be used in both codemods but i had a problem with this it seems i needed to keep getNewskitImports in this file in order for the component name not to be undefined

2022-08-15 07:47 UTC, mutebg commented on lib/codemod/src/transforms/update-linkinline.js
> +const removeLink = (j, root, list) => {
the problems come from the way you export/import functions, ping me and I will show you how to do it .

2022-08-15 08:05 UTC, mutebg requested changes

2022-08-17 09:42 UTC, baburay23 commented on lib/codemod/src/transforms/update-linkstandalone.js
> +};
i did this for the link component ones but i noticed with the one used in the Enum file that Xin did it has two parameters. This is because it maps over an array already in the enum-to-union file called  `enumNames` in my removeImports function I have had to include an extra parameter called List which looks through the import list and removes Link.

2022-08-17 10:45 UTC, baburay23 commented on lib/codemod/src/transforms/update-linkstandalone.js
> +      }
ah thanks so much! i have removed addImports now and refactored now!

2022-08-17 13:13 UTC, mutebg commented on lib/codemod/src/transforms/update-linkinline.js
> +    tagReplacement(j, createClosingTags, 'LinkInline');
Hey, can we abstract that function and make it more generic something similar to importReplace
```
tagReplace(j, root, 'Link', 'LinkInline');

tagReplace(j, root, 'Link', 'linkStandalone');
```

2022-08-18 10:25 UTC, baburay23 commented on lib/codemod/src/transforms/update-linkinline.js
> +    tagReplacement(j, createClosingTags, 'LinkInline');
hey sorry for the delay,
after our chat i made the relevant changes   `tagReplacement(j, root, 'Link', 'LinkInline');`
I think i was going wrong because I was passing a parameter of 'Link' when it actually needed the root path
<img width="646" alt="Screenshot 2022-08-18 at 11 25 02" src="https://user-images.githubusercontent.com/54642337/185373259-b1c9d004-f4c4-44f8-b403-bd5b0f5c23e8.png">
.

2022-08-18 11:16 UTC, mstuartf commented on lib/codemod/src/utils.js
> +      name: 'Link',
Should this be `_oldTags`?

2022-08-18 11:16 UTC, mstuartf commented on lib/codemod/src/utils.js
> +      name: 'Link',
Same here.

2022-08-18 11:16 UTC, mstuartf commented on lib/codemod/src/utils.js
> +function tagReplacement(j, root, _oldTags, newTags) {
A few notes on these params:
* What is `j`?
* Why does `_oldTags` have an underscore?
* Can we make the tags params singular as it looks like you only pass one tag to each?

2022-08-18 11:16 UTC, mstuartf commented on lib/codemod/src/transforms/update-linkstandalone.js
> +  tagReplacement(j, root, 'Link', 'LinkStandalone');
Suggest using a similar naming pattern for these functions - i.e. `replaceTags`?

2022-08-18 11:16 UTC, mstuartf commented on lib/codemod/README.md
> +-  import {Link} from 'newskit';
Ah I see this is because in `checkbox.tsx`, `Link` is not imported from `newskit`: 

`import {Link} from '../../components/link';`

2022-08-18 11:16 UTC, mstuartf commented on lib/codemod/src/transforms/update-linkinline.js
> +module.exports = function transformer(file, api) {
Since `Link` is quite a generic component name, do we need to worry about accidentally replacing `Link` components that aren't ours?

2022-08-18 11:53 UTC, baburay23 commented on lib/codemod/src/transforms/update-linkinline.js
> +module.exports = function transformer(file, api) {
I had a look at the code and i do not think this is a problem. This only replaces the Link component when it is inside the Newskit import 
`import {Block, InlineMessage, toNewsKitIcon, Link} from 'newskit';`
TO 
`import {Block, InlineMessage, toNewsKitIcon, LinkInline} from 'newskit';`
it will not remove ones outside it

2022-08-18 11:54 UTC, baburay23 commented on lib/codemod/README.md
> +-  import {Link} from 'newskit';
ah yes sorry it only works when you do `import {Block, InlineMessage, toNewsKitIcon, Link} from 'newskit';`

2022-08-18 12:16 UTC, baburay23 commented on lib/codemod/src/transforms/update-linkinline.js
> +    tagReplacement(j, createClosingTags, 'LinkInline');
ok sorry for the essay. I ended up fixing this and using the oldTag params as well, `tagReplacement `now takes four params as requested

2022-08-18 13:09 UTC, baburay23 commented on lib/codemod/src/utils.js
> +      name: 'Link',
sorry i had a problem with this function and now its been fixed. I need to use root to find the actual Link component. and the name of the component has now been changed to `oldTags` i cannot used oldTags.find (this is something i was doing originally and it did not work the error was `oldTags` is not a function.

2022-08-18 13:15 UTC, baburay23 commented on lib/codemod/src/utils.js
> +function tagReplacement(j, root, _oldTags, newTags) {
j holds all the jscodeshift functions these ones [https://npmdoc.github.io/node-npmdoc-jscodeshift/build/apidoc.html#apidoc.tableOfContents](url)
I use j to access the JSXOpeningElement and JSXClosingElement.
I have changed the params name to singular.
I have now removed underscore from `oldTag` I put it there originally as i thought `oldTag` as a parameter was needed but I was not using it inside the function. 
Eslint suggested I use _ if i want to keep it.  That was a mistake and I have now amended it. 
The `oldTag `parameter is now being used

2022-08-18 14:01 UTC, mstuartf commented on lib/codemod/src/utils/component-utils.js
> +  const name = oldTag.find(j.JSXIdentifier, {name: 'Link'});
Is it possible to abstract this and pass in `Link`?

2022-08-19 05:48 UTC, mutebg commented on lib/codemod/src/transforms/update-linkinline.js
> +module.exports = function transformer(file, api) {
That's a good one, we should consider that for example, they might have used Link from nextjs or any other library.

2022-08-19 05:49 UTC, mutebg commented on lib/codemod/src/transforms/update-linkstandalone.js
> +  return root.toSource();
This looks much neater now, good job :)

2022-08-19 05:50 UTC, mutebg commented on lib/codemod/src/utils/component-utils.js
> +  root.find(j.ImportDeclaration, {source: {value: 'newskit'}}).nodes();
let's add this function to the exports, it can be used in other codemods

2022-08-19 08:04 UTC, baburay23 commented on lib/codemod/src/transforms/update-linkinline.js
> +module.exports = function transformer(file, api) {
@mutebg is this something i should add in the replaceTag script?

2022-08-19 17:02 UTC, baburay23 commented on lib/codemod/src/transforms/update-linkinline.js
> +module.exports = function transformer(file, api) {
@mutebg @mstuartf i have now added some logic to the imports tag.
if you now run the codemod against the checkbox.tsx files nothing will happen, If a link component is being used outside the newskit import tag it wont run. 
I have also added a few tests after talking to Mike. 
For now I have only written these tests for `LinkInline` as i wanted to check if they were working.  Is it ok to add then to` Linkstandalone `too? 
sorry to ask i was just wary of having so many actual /expect files. Seems like i cannot add them into one file due to the imports

2022-08-22 05:59 UTC, mutebg approved these changes

2022-08-22 05:59 UTC, mutebg commented on lib/codemod/src/transforms/update-linkinline.js
> +module.exports = function transformer(file, api) {
IMO is NOT needed to add tests for both links, the functionality is quite generic, and it's quite a good approach. The only think I would change is the name of the function `replaceImports` because not only updates the imports but also the components. Maybe rename it to "replaceComponent" or "renameComponent" apart of that, its really nice codemod and we have generic function that can be used in the future !

2022-08-22 08:13 UTC, mstuartf approved these changes

2022-08-22 08:52 UTC, mutebg commented on lib/codemod/src/transforms/__tests__/update-linkinline/actual-link-alias.js
> +/*eslint import/no-unresolved: */
I think is better if you add some new regex to `.eslintignore` something like:
```
src/transforms/__tests__/**/expected*.js
src/transforms/__tests__/**/actual*.js
```

2022-08-22 10:21 UTC, mutebg approved these changes

2022-08-22 10:24 UTC, mstuartf approved these changes

2022-08-22 10:39 UTC, merged