docs(PPDSC-2297): NewsKit homepage update - banners, explore and more
newscorp-ghfb/newskit pull request #336
Opened 2022-08-16 10:26 UTC by evgenitsn

PPDSC-2297

**What**

Added new sections to the new NewsKit homepage:
- World Design Systems Week 2022 banner
- Explore
- Contribute banner
- Keep in touch
- Supported brands

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-08-16 10:36 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2297-newskit-homepage-update-banner-contribute-explore-more
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2297-newskit-homepage-update-banner-contribute-explore-more/storybook

2022-08-22 06:16 UTC, mutebg requested changes

2022-08-22 06:16 UTC, mutebg commented on site/components/homepage/supported-brands/supported-brands.tsx
> +          <GridLayoutItem key={getSSRId()}>
Don't use `getSSRid` here, better to use URL as a key since is unique. 
getSSRid will generate new keys on every re-render which is like having no keys.
When you need unique keys you might try with `useReactKeys` hook

2022-08-22 06:16 UTC, mutebg commented on site/components/homepage/keep-in-touch/keep-in-touch.tsx
> +            </Tag>
Why do you need this Tag here?

2022-08-22 06:16 UTC, mutebg commented on site/components/homepage/keep-in-touch/keep-in-touch.tsx
> +          <Block marginBlockEnd="space040">
I belive Headline and TextBlock should support logical props / margin, so it can be applied there instead of having extra blocks

2022-08-22 06:16 UTC, mutebg commented on site/components/homepage/explore/explore.tsx
> +          <Block marginBlockEnd="space040">
Same here, you don't need blocks, just apply margins on the headline and textblock

2022-08-22 06:41 UTC, evgenitsn commented on site/components/homepage/supported-brands/supported-brands.tsx
> +          <GridLayoutItem key={getSSRId()}>
For some weird reason using the `url` as key here generates very weird output 👇 

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/7677924/185853376-39874138-bc19-4be9-aef4-dc3eb16198b1.png">

That's why I went to `getSSRId`. I am now testing it with `useReactKeys` and it seems to work fine. I would update it

2022-08-22 06:42 UTC, evgenitsn commented on site/components/homepage/keep-in-touch/keep-in-touch.tsx
> +            </Tag>
I've added it because I was following the Figma designs and there was a Tag component wrapping the Links but I guess that could be a quirk of Figma. Looks like we don't need it. I just updated the `<LinkStandalone/>` style preset to support `iconColor` and moved the Icon as a children of it and now looks the same without the `<Tag/>`.

2022-08-22 06:42 UTC, evgenitsn commented on site/components/homepage/keep-in-touch/keep-in-touch.tsx
> +          <Block marginBlockEnd="space040">
Correct, I guess this is a leftover from reusing a <Card/> implementation from another old newskit page. Fixed.

2022-08-22 06:42 UTC, evgenitsn commented on site/components/homepage/explore/explore.tsx
> +          <Block marginBlockEnd="space040">
Done.

2022-08-22 06:49 UTC, mutebg commented on site/components/homepage/supported-brands/supported-brands.tsx
> +  const [brandLogoKey] = useReactKeys(1);
This works in a bit different way, now you are using the same key for every brand
```
const keys = useReactKeys(brandsLogos.lenght)
// later
<GridLayoutItem key={keys[index]}>
```

2022-08-22 09:23 UTC, evgenitsn commented on site/components/homepage/explore/explore.tsx
> +          <Block marginBlockEnd="space040">
Yeah, sorry 😬. This one slipped out. Should be good now.

2022-08-22 09:33 UTC, mutebg approved these changes

2022-08-22 13:08 UTC, Vanals approved these changes

2022-08-22 13:56 UTC, merged