Feat/ppdsc 2396 update pointer distance
newscorp-ghfb/newskit pull request #365
Opened 2022-09-08 10:47 UTC by jannuk59

PPDSC-XXXX

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-09-08 11:26 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2396-update-pointer-distance
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2396-update-pointer-distance/storybook

2022-09-12 11:53 UTC, evgenitsn requested changes

2022-09-12 11:53 UTC, evgenitsn commented on src/popover/__tests__/popover.stories.tsx
> +            overrides={{distance: 'space0', maxWidth: '300px'}}
`space0` is invalid token, can we update this to `space000`?

2022-09-12 11:53 UTC, evgenitsn commented on src/tooltip/__tests__/tooltip.stories.tsx
> +      overrides={{distance: 'space0'}}
same here

2022-09-12 12:21 UTC, evgenitsn commented
Can you please update the PR name to follow the convention?
Example: https://github.com/newscorp-ghfb/newskit/pull/370

2022-09-13 06:05 UTC, mutebg approved these changes

2022-09-13 08:43 UTC, evgenitsn approved these changes

2022-09-13 14:06 UTC, merged