feat(PPDSC-2145): add more menu storybook scenarios
newscorp-ghfb/newskit pull request #374
Opened 2022-09-15 13:54 UTC by evgenitsn

PPDSC-2145

**What**

Added 3 new scenarios into 2 new pages under `menu` section about:
- 2 tier level menu navigation
- 3 tier level menu navigation
- mobile accordion navigation with sub-sections
(Screenshots below)

There was another part of this ticket about creating a scenario for audio player with tooltips attached to the buttons but due to internal audio player limitation we can't implement that at the moment. The issue is that when we Play the audio track the tooltips are flickering because of a re-rendering. 
If we want to have this we need to add tooltip support for the audio player sub-components internally. 

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [x] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [x] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**After:**
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/7677924/190420501-e899d444-e488-41e9-8f7d-f01fad47fe23.png">
<img width="457" alt="image" src="https://user-images.githubusercontent.com/7677924/190420545-ce2dbf53-8f20-4d65-9553-a211ebf36c84.png">

**Who should review this PR:**

**How to test:**

2022-09-15 14:01 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2145-menu-storybook-scenarios
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2145-menu-storybook-scenarios/storybook

2022-09-20 11:25 UTC, baburay23 approved these changes

2022-09-20 15:35 UTC, mstuartf reviewed
Do the examples need to be interactive?

2022-09-21 05:01 UTC, mutebg requested changes

2022-09-21 05:01 UTC, mutebg commented on src/menu/__tests__/menu.stories.tsx
> +
This implementation does not seem right to me, it's again going to the previous comment with the correct HTML structure.
Also when the menu is closed it needs to be hidden, so that all links are still in the DOM but not visible.

2022-09-21 07:18 UTC, evgenitsn commented
After a discussion with Stoyan about this. The current stories implementation is not semantically correct because it's not actually a sub-menus (second, third level) but just two or three independent menus.
The correct way would be to have a single menu and then inside to have nested menus attached to the top-level menu items. 

We currently have 2/3 separate menus without any semantic connection between them. This would be confusing for the screen readers and the tab order.

With our current Menu components we don't have the ability to create such nested menus that are semantically correct. 
We have to first investigate how to do this, then to update the Menu internal component to support this. When that's done it would be possible for us to make these scenarios in a correct way.

I am closing this PR now and will use it as a reference for the spike that I just created https://nidigitalsolutions.jira.com/browse/PPDSC-2433

2022-09-21 07:18 UTC, closed without merging