docs(PPDSC-2381): Tag documentation
newscorp-ghfb/newskit pull request #402
Opened 2022-10-07 12:43 UTC by RashikaNewsUK

PPDSC-2381

**What**

1.Tag documentation UI.

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-10-07 12:53 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2381-tag-documentation
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2381-tag-documentation/storybook

2022-10-11 09:19 UTC, mstuartf commented on cypress/site/functional/section-navigation.spec.js
> +    cy.mockConsentAndVisit('/components/text-input');
Why does this need to be changed?

2022-10-11 09:19 UTC, mstuartf commented on site/pages/components/tag.tsx
> +    description: 'If true, renders the undefined tag in a disabled state.',
What does `undefined` mean in this context? Might be a question for Mike M.

2022-10-12 05:00 UTC, Srinivasan-Ramasamy commented on cypress/site/functional/section-navigation.spec.js
> +    cy.mockConsentAndVisit('/components/text-input');
Hi **@mstuartf**, Section navigation spec has cypress test scenario to check links in .mdx file. Actually part of current tag documentation changes we've removed the tag.mdx file. So we've updated the spec js with text-input.mdx file name to pass the build.

2022-10-14 07:52 UTC, RashikaNewsUK commented on site/pages/components/tag.tsx
> +    description: 'If true, renders the undefined tag in a disabled state.',
Hi @mstuartf,
I have removed the word "**undefined**" from the API section. Could you please take look and confirm.

Thanks,
Rashika.

2022-10-14 13:01 UTC, Vanals commented on site/components/illustrations/components/tag/behaviours/fixedandfullwidth.tsx
> +import {Svg} from '../../../svg';
should this file be using kebab case!? If came like that probably should have been renamed correctly in figma in first place :)

2022-10-14 13:52 UTC, RashikaNewsUK commented on site/components/illustrations/components/tag/behaviours/fixedandfullwidth.tsx
> +import {Svg} from '../../../svg';
Hi @Vanals,

This is my mistake,while working on this doc I have modified the file name without any space. I am not aware about that.Apologize for that. I have corrected the file name according to the figma and will also correct on upcoming story as well.

Thanks,
Rashika.

2022-10-17 07:29 UTC, mutebg requested changes

2022-10-17 07:29 UTC, mutebg commented on site/pages/components/tag.tsx
> +  },
this does not exist, can be removed

2022-10-17 07:29 UTC, mutebg commented on site/pages/components/tag.tsx
> +  },
You can delete this one, its a duplicate. Bellow you have minHeight one more time

2022-10-17 07:29 UTC, mutebg commented on site/pages/components/tag.tsx
> +    default: ['backgroundColorChange', 'borderColorChange'],
```suggestion
    default: ['backgroundColorChange'],
```

2022-10-17 07:29 UTC, mutebg commented on site/pages/components/tag.tsx
> +    attribute: 'tag.spaceInset',
```suggestion
    attribute: 'spaceInset',
```

2022-10-17 07:29 UTC, mutebg commented on site/pages/components/tag.tsx
> +    default: ['small = space010', 'medium = space010', 'large = space020'],
```suggestion
    default: ['small = space010', 'medium = space010', 'large = space010'],
```

2022-10-17 07:29 UTC, mutebg commented on site/pages/components/tag.tsx
> +    attribute: 'tag.icon.size',
```suggestion
    attribute: 'iconSize',
```

2022-10-17 07:29 UTC, mutebg commented on site/pages/components/tag.tsx
> +    default: ['small = space010', 'medium = space010', 'large = space020'],
```suggestion
    default: ['small = iconSize010', 'medium = iconSize010', 'large = iconSize020'],
```

2022-10-17 07:29 UTC, mutebg commented on site/pages/components/tag.tsx
> +                  stylePreset: 'tagCustom',
tagCustom does not exist try with:
```suggestion
                  stylePreset: 'tagPrimaryInverse',
```

2022-10-17 10:27 UTC, RashikaNewsUK commented on site/pages/components/tag.tsx
> +  },
I have removed the event originator form the api section. -thanks!

2022-10-17 10:28 UTC, RashikaNewsUK commented on site/pages/components/tag.tsx
> +    attribute: 'tag.stylePreset',
I have modified all the attributes name which mentioned here. -thanks!

2022-10-17 10:30 UTC, RashikaNewsUK commented on site/pages/components/tag.tsx
> +  },
I have removed this one as well. -thanks!

2022-10-17 10:30 UTC, RashikaNewsUK commented on site/pages/components/tag.tsx
> +    default: ['small = sizing090', 'medium = sizing100', 'large = sizing110'],
Done, I have removed the default. -thanks!

2022-10-17 10:31 UTC, RashikaNewsUK commented on site/pages/components/tag.tsx
> +    default: ['backgroundColorChange', 'borderColorChange'],
Done. Removed the "borderColorChange" from the default. -thanks!

2022-10-17 10:32 UTC, RashikaNewsUK commented on site/pages/components/tag.tsx
> +    default: ['small = space010', 'medium = space010', 'large = space020'],
Done. Modified the large value. -thanks!

2022-10-17 10:32 UTC, RashikaNewsUK commented on site/pages/components/tag.tsx
> +    default: ['small = space010', 'medium = space010', 'large = space020'],
Done. Modified the default values. -thanks!

2022-10-17 10:33 UTC, RashikaNewsUK commented on site/pages/components/tag.tsx
> +                  stylePreset: 'tagCustom',
Done. Modified the stylePreset value. -thanks!

2022-10-17 11:32 UTC, RashikaNewsUK commented on site/pages/components/tag.tsx
> +  },
Done

2022-10-17 11:45 UTC, mutebg approved these changes

2022-10-17 13:12 UTC, Srinivasan-Ramasamy approved these changes

2022-10-18 04:54 UTC, merged