Fix/ppdsc 2387 grid layout flag
newscorp-ghfb/newskit pull request #419
Opened 2022-10-18 08:39 UTC by LukeFinch

PPDSC-2387

**What**
Our Flag component ( and underlying ones like Tag, Button and so on ) use Stack under the hood, the main reason is to be able to have spaceInline between Flag children.

Using Stack adds a few extra children, and we can simplify the component using GridLayout.

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-10-18 09:03 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2387-grid-layout-flag
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2387-grid-layout-flag/storybook

2022-10-27 13:47 UTC, mutebg commented on src/button/styled.ts
>      logicalProps(
I belive we might not need this one as well, can you test if everything if we remove it

2022-10-27 13:47 UTC, mutebg commented on src/grid-layout/styled.ts
> +  ${/* LOGICAL_PROPS_TO_DO: spaceInset to be removed. */ ''}
You need to update the types.ts file as well

2022-10-28 12:55 UTC, LukeFinch commented on src/button/styled.ts
>      logicalProps(
Looks like it's okay to be removed - judging by applitools

2022-10-28 13:19 UTC, mutebg commented on src/flag/types.ts
> -  spaceInset?: MQ<string>;
Sorry, my bad,  This should stay here a well as in the grid-layout.

2022-10-28 13:20 UTC, mutebg commented on src/button/styled.ts
>      logicalProps(
Lets remove it, checking the logic for that component it wont be needed

2022-10-28 13:28 UTC, LukeFinch commented on src/flag/types.ts
> -  spaceInset?: MQ<string>;
Ah yeah - I was thinking the types extended the grid layout.

2022-10-28 13:29 UTC, LukeFinch commented on src/flag/types.ts
> -  spaceInset?: MQ<string>;
Fixed in the latest commit 👍

2022-10-31 05:45 UTC, mutebg requested changes

2022-10-31 05:45 UTC, mutebg commented on src/button/styled.ts
>      )}; // needs to be used in here as well, even though Flag uses it itself
Now I read this comment, that's not nice that we need to keep these double logical props because of some safari margin issues. 
My suggestion is to add padding and margin reset to GridLayout, and remove the margin reset and logical props from the button
```
margin: 0;
padding: 0;
```

2022-10-31 05:45 UTC, mutebg commented on src/flag/types.ts
> -  spaceInset?: MQ<string>;
Maybe you forgot to push it? I still see this removed

2022-10-31 13:15 UTC, mutebg approved these changes

2022-10-31 17:41 UTC, mstuartf submitted a review, later dismissed

2022-11-02 09:08 UTC, mutebg approved these changes

2022-11-02 10:00 UTC, mutebg approved these changes

2022-11-02 10:58 UTC, mstuartf approved these changes

2022-11-02 11:04 UTC, merged