docs(PPDSC-2346): Grid cell documentation
newscorp-ghfb/newskit pull request #420
Opened 2022-10-18 11:13 UTC by RashikaNewsUK

PPDSC-2346

**What**

1.Grid-Cell documentation UI.

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [X] Updated relevant documentation

**I have tested manually:**
- [X] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [X] The screen reader reads and flows through the elements as expected.
- [X] There are no new errors in the browser console coming from this PR.
- [X] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-10-18 11:25 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2346-grid-cell-documentation
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2346-grid-cell-documentation/storybook

2022-10-21 06:15 UTC, mutebg requested changes

2022-10-21 06:15 UTC, mutebg commented on site/pages/components/grid.tsx
> +              name: 'Root',
```suggestion
              name: 'children',
```

2022-10-21 06:15 UTC, mutebg commented on site/pages/components/grid.tsx
> +            },
Tihs does not seems correct, we have the following props:
```
  xs?: number | 'full-width';
  sm?: number | 'full-width';
  md?: number | 'full-width';
  lg?: number | 'full-width';
  xl?: number | 'full-width';

  xsHidden?: boolean;
  smHidden?: boolean;
  mdHidden?: boolean;
  lgHidden?: boolean;
  xlHidden?: boolean;

  xsOrder?: number;
  smOrder?: number;
  mdOrder?: number;
  lgOrder?: number;
  xlOrder?: number;

  xsOffset?: number;
  smOffset?: number;
  mdOffset?: number;
  lgOffset?: number;
  xlOffset?: number;
```

2022-10-26 07:50 UTC, RashikaNewsUK commented on site/pages/components/grid.tsx
> +            },
Hi @mutebg ,
All the changes has been done. Please have a look on it.
Thanks,
Rashika

2022-10-26 13:44 UTC, mutebg commented on site/pages/components/grid.tsx
> +const commonPropsRows = [
```suggestion
const gridPropsRows = [
```

2022-10-26 14:41 UTC, RashikaNewsUK commented on site/pages/components/grid.tsx
> +              name: 'Children',
Hi @mutebg , 
changes has been done, Please have a look on it. -thanks!

2022-10-27 05:52 UTC, mutebg approved these changes

2022-10-28 07:39 UTC, Srinivasan-Ramasamy approved these changes

2022-10-28 10:28 UTC, merged