Docs/ppdse 2340 update spcae pages
newscorp-ghfb/newskit pull request #443
Opened 2022-10-28 09:49 UTC by baburay23

PPDSC-XXXX

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-10-28 10:01 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdse-2340-update-spcae-pages
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdse-2340-update-spcae-pages/storybook

2022-10-31 10:51 UTC, Xin00163 reviewed
Looks good. I noticed in the design spec that `spaceInset` & `spaceStack` are removed. We haven't deprecated them yet. Is it OK to remove from docs?

2022-10-31 13:27 UTC, Xin00163 approved these changes

2022-10-31 13:43 UTC, LukeFinch commented
Hi Aysha,
In the designs, it looks as though we're purposefully adding line breaks in the paragraphs to stop the line lengths from running on for too long. 

Perhaps we could try adding a max-width to the text blocks so that they don't go too wide on larger viewports?
Something like `max-width: 60ch` - or perhaps a number of column spans? 

I'd consult with the design team as it looks intentional on their end.

2022-10-31 14:27 UTC, LukeFinch requested changes

2022-10-31 14:27 UTC, LukeFinch commented on site/pages/theme/foundation/spacing.tsx
> +          headline="Space Tokens"
Lower case T in designs. `Space tokens` versus `Space Tokens`

2022-10-31 14:41 UTC, LukeFinch commented
> 

https://nidigitalsolutions.jira.com/browse/PPDSC-2535
Mike's got a ticket in the backlog saying the layout of these pages has regressed.

2022-10-31 15:14 UTC, LukeFinch approved these changes

2022-10-31 15:48 UTC, merged