docs(PPDSC-2388): link-documentation
newscorp-ghfb/newskit pull request #444
Opened 2022-10-31 11:26 UTC by RashikaNewsUK

PPDSC-2388

**What**

1. Link documentation UI.

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [x] Updated relevant documentation

**I have tested manually:**
- [x] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [x] The screen reader reads and flows through the elements as expected.
- [x] There are no new errors in the browser console coming from this PR.
- [x] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [x] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-10-31 11:37 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2388-link-documentation
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2388-link-documentation/storybook

2022-11-03 15:02 UTC, mutebg commented on site/pages/components/link.tsx
> +          title: 'Link',
IMO we should have 2 separate components, LinkInline and LinkStandalone

2022-11-03 15:02 UTC, mutebg commented on site/pages/components/link.tsx
> +            },
All overrides should be without `inlineLink` and `standaloneLink` and again we need to have 2 tables

2022-11-04 05:10 UTC, RashikaNewsUK commented on site/pages/components/link.tsx
> +            },
Sure @mutebg , Let me check. -thanks!

2022-11-04 05:10 UTC, RashikaNewsUK commented on site/pages/components/link.tsx
> +            },
@mutebg  Shall I remove this?

2022-11-04 05:11 UTC, RashikaNewsUK commented on site/pages/components/link.tsx
> +          title: 'Link',
Will check this @mutebg

2022-11-04 05:23 UTC, RashikaNewsUK commented on site/pages/components/link.tsx
> +            },
@mutebg , Should we need to have separate tables for **inlineLink** and **standaloneLink**?

2022-11-04 05:24 UTC, RashikaNewsUK commented on site/pages/components/link.tsx
> +        illustration: 'components/url-illustration',
will modify. -thanks!

2022-11-07 07:10 UTC, mutebg commented on site/pages/components/link.tsx
> +            },
sorry but this is not correct, the logical props are the same as Fieldset for example.
![Screenshot 2022-11-07 at 9 09 39](https://user-images.githubusercontent.com/3543332/200246682-fe0a11e3-3ea6-436f-a350-06b81bfb6d3f.png)

2022-11-07 10:54 UTC, RashikaNewsUK commented on site/pages/components/link.tsx
> +            },
Hi @mutebg ,
the changes has been done. Please have a look on it. -thanks!

2022-11-08 07:18 UTC, mutebg commented on site/pages/components/link.tsx
> +                aria-label="props link info"
You have an accessibility error, I think it comes from that InlineMessage and the fact you have 2 messages with the same aria-label.
```suggestion
                aria-label="props LinkInline info"
```

2022-11-08 07:19 UTC, mutebg commented on site/pages/components/link.tsx
> +                aria-label="props link info"
```suggestion
                aria-label="props LinkStandalone info"
```

2022-11-08 11:55 UTC, mutebg requested changes

2022-11-08 11:55 UTC, mutebg commented on site/pages/components/link.tsx
> +              ),
here you need to do it the same way as the other component

2022-11-08 13:37 UTC, RashikaNewsUK commented on site/pages/components/link.tsx
> +              ),
Let me check and update @mutebg

2022-11-08 14:05 UTC, RashikaNewsUK commented on site/pages/components/link.tsx
> +              ),
@mutebg  the changes has been done.Apologize for before review request. thanks!

2022-11-09 09:34 UTC, mutebg approved these changes

2022-11-10 14:20 UTC, Xin00163 commented on site/pages/components/link.tsx
> +        tableRows: [
Didn't see this in the spec. Is this needed?

2022-11-10 14:29 UTC, Xin00163 commented on site/pages/components/link.tsx
> +        'https://www.figma.com/file/FSbCQa6SzVR3K48ZWLeD77/%F0%9F%9F%A2-NK-Web-Components?node-id=324%3A4',
I think now @mstuartf merged https://github.com/newscorp-ghfb/newskit/pull/449/. You will need to add storybookId like this [site/pages/components/button.tsx](https://github.com/newscorp-ghfb/newskit/pull/449/files#diff-455ba27a2d6bacd97fd3d2cebef9d286dce091e21453e55b6995ea3528240057R171)

2022-11-11 04:15 UTC, RashikaNewsUK commented on site/pages/components/link.tsx
> +        'https://www.figma.com/file/FSbCQa6SzVR3K48ZWLeD77/%F0%9F%9F%A2-NK-Web-Components?node-id=324%3A4',
Hi @Xin00163 ,
Thanks for your review.
Are you telling like this?
{
            title: 'Link',
            page: true,
            **id: 'site/pages/components/link.tsx',**
            description:
              'Links allow users to navigate to a new location or to additional information.',
            illustration: 'components/url-illustration',
          },

2022-11-11 04:27 UTC, RashikaNewsUK commented on site/pages/components/link.tsx
> +        tableRows: [
@Xin00163 this has been mentioned in the design link, so I have added. could you please refer this link FYR?  [https://www.figma.com/file/jj2dNnE0yZ9D1vYf14TFQe/02---NK-Web---Link?node-id=2034%3A315102&t=CiGvCXAt3EsPWouw-0](url)

2022-11-11 05:18 UTC, RashikaNewsUK commented on site/pages/components/link.tsx
> +        'https://www.figma.com/file/FSbCQa6SzVR3K48ZWLeD77/%F0%9F%9F%A2-NK-Web-Components?node-id=324%3A4',
@Xin00163 added. Please have a look on it. thanks!

2022-11-11 08:23 UTC, mutebg approved these changes

2022-11-11 12:46 UTC, Xin00163 approved these changes

2022-11-14 07:37 UTC, merged