docs(PPDSC-2323): add event tracking to toc
newscorp-ghfb/newskit pull request #460
Opened 2022-11-04 12:26 UTC by mutebg

PPDSC-2323

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-11-04 12:38 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2323-track-scroll-depth
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2323-track-scroll-depth/storybook

2022-11-08 09:20 UTC, Xin00163 commented on site/pages/_app.tsx
> +    console.log({pageProps});
still needed?

2022-11-08 09:29 UTC, baburay23 approved these changes

2022-11-08 09:38 UTC, Xin00163 commented on site/components/table-of-contents/table-of-contents.tsx
> +    <InstrumentationProvider context={{area: 'toc-navigation'}}>
I wondered if I am supposed to see `toc-navigation`
Here is what I got:
```context: {pageOriginator: 'inline-message', pageType: 'ppdsc-2323-track-scroll-depth', area: 'main content', section: 'interactive-demo'}
```

2022-11-08 12:15 UTC, mutebg commented on site/components/table-of-contents/table-of-contents.tsx
> +    <InstrumentationProvider context={{area: 'toc-navigation'}}>
When you click on the link or when you scroll, these are 2 different events?

when you scroll you should see:
```
{
context: {
   area: 'main content', 
   section: 'anatomy'
},
originator: "page-scroll",
trigger:  "scroll"
}
```

and when you click on the links that is a different event
```
{
context:  {
   area: 'toc-navigation', href: '/ppdsc-2323-track-scroll-depth/components/checkbox/#states', 
   value: 'States'
},
originator:  "link",
trigger: "click",
}
```

2022-11-08 13:52 UTC, Xin00163 commented on site/pages/_app.tsx
> +    console.log({pageProps});
Still logging pageProps

2022-11-08 15:30 UTC, Vanals requested changes

2022-11-08 15:30 UTC, Vanals commented on site/components/table-of-contents/table-of-contents.tsx
> +        fireEvent(data);
I am a bit unsure why we need this 🤔  I have had a look at the PR website and I can see we already have in place a 'page-scroll' event tracker AND a link event tracker.

TOC is triggered by clicking a link and then scrolls down to the designated area... so we have already event tracking this happening, why do we need an extra event to track this action? an extra set of information? isn't what we are sending enough? feels a bit overkilling. Let me know if I am missing something

Also if must be tracket, I would maybe differentiate this event from the "normal" `page-scrolling` event. I would call it differently to specify this is the event where a TOC section gets selected like 'toc-section-selection', not really the scrolling

2022-11-08 15:44 UTC, Vanals approved these changes

2022-11-08 15:58 UTC, mstuartf submitted a review, later dismissed

2022-11-09 09:51 UTC, mutebg commented on site/pages/_app.tsx
> +    console.log({pageProps});
thanks, removed

2022-11-09 12:06 UTC, Xin00163 approved these changes

2022-11-09 16:01 UTC, mstuartf approved these changes

2022-11-10 06:42 UTC, merged