fix(PPDSC-2634): select panel zindex
newscorp-ghfb/newskit pull request #527
Opened 2022-12-20 13:34 UTC by mutebg

PPDSC-2634

**What**

1. Background - the select panel goes over other elements with fixed position and z-index -> https://codesandbox.io/s/busy-stonebraker-rdxer2?file=/src/App.tsx
2. What did you do - the `select panel` is rendered inside a `layer organizer`, which means it has its own stacking context and is on top of everything. However, there are some cases you want to have a fixed header or other elements on top of that. In order to solve this I added `zIndex` as an override to the panel. By default uses the keyword "layer" which keeps the current behaviour ( rendering in a layer organizer ) but users can override that by passing a `z-index` value which applies to the panel.
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-12-20 14:12 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2634-select-panel-zindex
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2634-select-panel-zindex/storybook

2022-12-22 13:08 UTC, JohnTParsons requested changes

2022-12-22 13:08 UTC, JohnTParsons commented on site/pages/components/select.tsx
> +      'If provided, this overrides the zIndex of the Modal. When set to "layer" the panel renders in LayerOrganizer ',
Replace `LayerOrganizer '` with `LayerOrganizer.'`

2022-12-29 09:16 UTC, JohnTParsons approved these changes

2022-12-29 09:31 UTC, baburay23 approved these changes

2022-12-29 10:11 UTC, merged