docs(PPDSC-2538) breadcrumbs documentation
newscorp-ghfb/newskit pull request #528
Opened 2022-12-22 11:47 UTC by RashikaNewsUK

PPDSC-2538

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [X] Updated relevant documentation

**I have tested manually:**
- [X] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [X] The screen reader reads and flows through the elements as expected.
- [X] There are no new errors in the browser console coming from this PR.
- [X] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [X] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2022-12-22 12:07 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2538-breadcrumbs-documentation
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2538-breadcrumbs-documentation/storybook

2022-12-22 12:10 UTC, JohnTParsons approved these changes

2022-12-28 09:18 UTC, JohnTParsons submitted a review, later dismissed

2022-12-30 07:17 UTC, mutebg requested changes

2022-12-30 07:17 UTC, mutebg commented on site/pages/components/breadcrumbs.tsx
> +            attribute: 'arialabel',
this is `aria-current`

2022-12-30 07:17 UTC, mutebg commented on site/pages/components/breadcrumbs.tsx
> +            attribute: 'arialabel',
i thnk the attribute is `aria-label`

2022-12-30 07:17 UTC, mutebg commented on site/pages/components/breadcrumbs.tsx
> +            },
Can you move this row up, before `separator.stylePreset` one

2022-12-30 07:17 UTC, mutebg commented on site/pages/components/breadcrumbs.tsx
> +              default: 'paddingInline: space020',
```suggestion
              default: 'space020',
```

2022-12-30 07:17 UTC, mutebg commented on site/pages/components/breadcrumbs.tsx
> +                'large - iconSize030',
```suggestion
                'small - utilityButton010',
                'medium - utilityButton020',
                'large - utilityButton030',
```

2023-01-03 10:20 UTC, RashikaNewsUK commented on site/pages/components/breadcrumbs.tsx
> +                'large - iconSize030',
@mutebg all the changes has been done. Please have a look on it

2023-01-03 10:23 UTC, mutebg approved these changes

2023-01-03 10:41 UTC, baburay23 submitted a review, later dismissed

2023-01-03 12:15 UTC, baburay23 approved these changes

2023-01-03 12:23 UTC, merged