docs(PPDSC-2653): fix console errors on homepage
newscorp-ghfb/newskit pull request #544
Opened 2023-01-05 08:04 UTC by evgenitsn

PPDSC-2653

**What**

1. Background - There was a few console errors and warning on the docs home page 
2. What did you do - Fixed them
3. What does the reviewers should expect - No errors in the browser console on home page

**I have done:**
- [] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [x] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [x] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-01-05 08:11 UTC, newskit-engineering commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2653-fix-console-errors-on-homepage
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2653-fix-console-errors-on-homepage/storybook

2023-01-05 09:14 UTC, JohnTParsons submitted a review, later dismissed

2023-01-05 11:42 UTC, mutebg requested changes

2023-01-05 11:42 UTC, mutebg commented on src/audio-player-composable/components/volume-control/volume-control.tsx
> +            nodeRef={cssTransitionNodeRef}
can you explain what's going on here, why do we need that on every component that has CSS transition?

2023-01-05 11:42 UTC, mutebg commented on src/audio-player-composable/components/volume-control/volume-control.tsx
> +              <div ref={cssTransitionNodeRef}>
can you pass the ref directly to StyledVolumeSliderContainer? I personally don't like adding extra div elements

2023-01-05 13:00 UTC, evgenitsn commented on src/audio-player-composable/components/volume-control/volume-control.tsx
> +            nodeRef={cssTransitionNodeRef}
There was an error in the console 

> Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node

After some research I found out that it is coming from react-transition-group package and this is the issue and the proposed solution. 
https://github.com/reactjs/react-transition-group/issues/668#issuecomment-695162879

This is also present in their official docs (first example): https://reactcommunity.org/react-transition-group/css-transition

2023-01-05 13:00 UTC, evgenitsn commented on src/audio-player-composable/components/volume-control/volume-control.tsx
> +              <div ref={cssTransitionNodeRef}>
Following the my other comment, we have to have the `ref` prop to avoid the error in the console. It may be a good idea to try and pass it to the outermost node in this case `StyledVolumeSliderContainer`. I will check that and will update where is possible.

2023-01-05 13:13 UTC, mutebg commented on src/audio-player-composable/components/volume-control/volume-control.tsx
> +              <div ref={cssTransitionNodeRef}>
Can you do that for all components where you pass an extra div, I don't see why wound't work

2023-01-06 09:37 UTC, mstuartf commented on src/audio-player-composable/components/volume-control/volume-control.tsx
> +              <div ref={cssTransitionNodeRef}>
Solution looks good but I agree we should just be able to pass to the existing element, rather then wrapping in a new div.

2023-01-06 10:32 UTC, evgenitsn commented on src/audio-player-composable/components/volume-control/volume-control.tsx
> +              <div ref={cssTransitionNodeRef}>
Thanks for the review, I've just updated the components. No more wrapping divs, just passing the ref to the original parent. @mutebg @mstuartf

2023-01-09 09:30 UTC, mutebg approved these changes

2023-01-09 16:25 UTC, baburay23 approved these changes

2023-01-10 12:14 UTC, merged