chore(PPDSC-2675): speed unit tests local run
newscorp-ghfb/newskit pull request #600
Opened 2023-02-02 18:00 UTC by Xin00163

PPDSC-2675

What I have done:

- Fix the disabled state in svg-previewer.tsx
- Update svg-previewer.test.tsx
- Update outdated docsite unit tests
- Increase local run maxWorker to 50% (this command is optional as not everyone wants to use 50%)

But if it's enabled, there is a dramatic difference:

Before:
![Screenshot 2023-02-01 at 10 33 49](https://user-images.githubusercontent.com/12214841/216404803-6ab84db6-34d4-4484-8efd-b01665704c41.png)

After:
![Screenshot 2023-02-02 at 17 51 54](https://user-images.githubusercontent.com/12214841/216404846-1600b913-223d-40b0-9b14-bf94696297aa.png)

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-02-02 18:05 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2675-unit-tests-slow
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2675-unit-tests-slow/storybook

2023-02-03 07:28 UTC, evgenitsn submitted a review, later dismissed

2023-02-03 13:26 UTC, JohnTParsons requested changes
Good work. I don't think you should be changing yarn.lock though as package.json has not changed

2023-02-03 16:06 UTC, Xin00163 commented
> Good work. I don't think you should be changing yarn.lock though as package.json has not changed

 I ran yarn upgrade interactive to upgrade the testing library package, which clearly was not needed. Now I need to revert it back

2023-02-06 13:29 UTC, mutebg approved these changes

2023-02-06 13:43 UTC, JohnTParsons approved these changes

2023-02-06 14:42 UTC, merged