feat(PPDSC-1940): remove Link component
newscorp-ghfb/newskit pull request #624
Opened 2023-02-10 14:00 UTC by evgenitsn

PPDSC-1940

**What**

1. Background - the Link component is deprecated so we can remove it now and replace it with LinkInline and LinkStandalone
2. What did you do - deleted the deprecated Link component 
3. What does the reviewers should expect - Link component replaced with LinkInline and LinkStandalone

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-02-13 08:17 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-1940-remove-link-component
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-1940-remove-link-component/storybook

2023-02-13 16:38 UTC, Vanals requested changes

2023-02-13 16:38 UTC, Vanals commented on site/.env.local
> +GOOGLE_SHEETS_CLIENT_EMAIL="newskit-local@quickstart-1578476313623.iam.gserviceaccount.com"
I think this should not be on gitHub, shouldn't it 👀 ? @evgenitsn

2023-02-13 16:44 UTC, Vanals commented on site/.env.local
> +GOOGLE_SHEETS_CLIENT_EMAIL="newskit-local@quickstart-1578476313623.iam.gserviceaccount.com"
I saw you were off so I have removed it just in case. But let me know tmr. I have saved the values in my local repo under `.env`

2023-02-14 06:36 UTC, mutebg approved these changes

2023-02-14 08:57 UTC, Vanals approved these changes

2023-02-14 10:50 UTC, merged