docs(PPDSC-2667) image documentation
newscorp-ghfb/newskit pull request #647
Opened 2023-02-17 06:46 UTC by RashikaNewsUK

PPDSC-2667

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-02-17 06:55 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2667-image-documentation
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2667-image-documentation/storybook

2023-02-21 16:22 UTC, mstuartf approved these changes

2023-02-22 06:38 UTC, mutebg requested changes

2023-02-22 06:38 UTC, mutebg commented on site/pages/components/image.tsx
> +  <ComponentPageTemplate
You can check how we started typing this template for example in Slider page.
```suggestion
  <ComponentPageTemplate<typeof Image>
```

2023-02-22 06:38 UTC, mutebg commented on site/pages/components/image.tsx
> +        ] as any,
Once you type the page, you can remove this `any`

2023-02-22 06:38 UTC, mutebg commented on site/pages/components/image.tsx
> +            },
This is not correct, can you please check how we do that in Sluder you need to do it like `...logicalMarginOverrideProps`

2023-02-24 04:14 UTC, RashikaNewsUK commented on site/pages/components/image.tsx
> +  <ComponentPageTemplate
@mutebg will check -thanks!

2023-02-24 04:16 UTC, RashikaNewsUK commented on site/pages/components/image.tsx
> +        ] as any,
@mutebg I have added this` any` to accept all the type of props. Is that need to change anything?

2023-02-24 04:17 UTC, RashikaNewsUK commented on site/pages/components/image.tsx
> +            },
Will check and modify, -thanks!

2023-02-24 08:52 UTC, mutebg commented on site/pages/components/image.tsx
> +          // {
Remove this comment if you don't need it

2023-02-24 11:17 UTC, mutebg approved these changes

2023-02-24 13:47 UTC, mstuartf approved these changes

2023-02-27 07:53 UTC, merged