feat(PPDSC-2838): use new s3 for pr links
newscorp-ghfb/newskit pull request #663
Opened 2023-02-23 11:32 UTC by Xin00163

PPDSC-2838

- Add new bucket for PR

Please note, we need to update the below in `ncu-newskit-site-pr` context once this ticket is merged.
```
SITE_BASE_URL
http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/
```

Right now clicking on other links are not working. Once the above is done, they will be working again. This has been tested.

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-02-23 11:40 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/ppdsc-2838-use-new-s3-for-pr
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/ppdsc-2838-use-new-s3-for-pr/storybook

2023-02-23 16:52 UTC, Xin00163 commented on .circleci/config.yml
> +          apply: true
@JohnTParsons do we need to set it to false now that we finished testing?

2023-02-24 10:11 UTC, JohnTParsons commented on .circleci/config.yml
> +          apply: true
No, that instance should always be true, as not just for validating TF upfront but for doing it upfront.

2023-02-24 10:13 UTC, JohnTParsons requested changes

2023-02-24 10:13 UTC, JohnTParsons commented on terraform/s3/dev-newskit/variables.tf
> +  default     = "ncu-newskit-docs-pr"
You can now delete that surplus space you added (to get the TF step to run)

2023-02-24 10:36 UTC, JohnTParsons commented on .circleci/config.yml
> +            node --version
"node --version" line could be removed

2023-02-24 11:32 UTC, JohnTParsons approved these changes

2023-02-24 12:34 UTC, baburay23 commented on site/pages/components/text-area.tsx
> -                href="http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2470-character-count-documentation/components/character-count/"
looks good to me just wanted to ask is this a mistake leftover from before? Wondering why it was referencing a particular PR link

2023-02-24 12:34 UTC, baburay23 approved these changes

2023-02-24 13:16 UTC, Xin00163 commented on site/pages/components/text-area.tsx
> -                href="http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2470-character-count-documentation/components/character-count/"
Yeah I think it's a mistake from before.

2023-02-24 16:24 UTC, merged