docs(PPDSC-2851): add inline-message to hooks page
newscorp-ghfb/newskit pull request #683
Opened 2023-03-02 12:57 UTC by mutebg

PPDSC-2851

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-03-02 13:05 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/ppdsc-2851-media-query-info-message
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/ppdsc-2851-media-query-info-message/storybook

2023-03-07 09:51 UTC, JohnTParsons requested changes

2023-03-07 09:51 UTC, JohnTParsons commented on site/pages/theme/foundation/colours.tsx
> +          'Use ‘common’ interactive tokens to indicate and display interactions of components that are links, or components in disabled, visited, and focus states.',
Suggest
```
visited and focus states
```

2023-03-07 10:00 UTC, mutebg commented on site/pages/theme/foundation/colours.tsx
> +          'Use ‘common’ interactive tokens to indicate and display interactions of components that are links, or components in disabled, visited, and focus states.',
sorry, now I see this is not coming from my commit, probably I need to update  PPDSC-0000-storybook-updates to main

2023-03-07 10:05 UTC, closed without merging