Docs/ppdsc 2707 update headline component storybook scenarios
newscorp-ghfb/newskit pull request #692
Opened 2023-03-08 09:14 UTC by jannuk59

PPDSC-XXXX

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-03-08 09:25 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/ppdsc-2707-update-headline-component-storybook-scenarios
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/ppdsc-2707-update-headline-component-storybook-scenarios/storybook

2023-03-20 08:20 UTC, JohnTParsons submitted a review, later dismissed

2023-03-20 08:25 UTC, mutebg requested changes

2023-03-20 08:25 UTC, mutebg commented on src/headline/__tests__/headline.stories.tsx
> +    </StorybookCase>
I think there is some misalignment.
These are render as stories you must use `<Headline as="h1" /> <Headline as="h2" />`  and so on, the same way you do that for the rest of the stories.

This story is about Headline component, we must not use Headings here ( h1,h2 and so on) lets cath up with Geri

2023-03-20 08:42 UTC, jannuk59 commented on src/headline/__tests__/headline.stories.tsx
> +    </StorybookCase>
@mutebg Makes a point. Shall I change it to headline? like `<Headline as="h1" /> <Headline as="h2" />` and push?

2023-03-20 08:59 UTC, mutebg commented on src/headline/__tests__/headline.stories.tsx
> +    </StorybookCase>
I am not sure if we need this, lets's talk with Geri

2023-03-20 12:22 UTC, mutebg commented on src/headline/__tests__/headline.stories.tsx
> +    </StorybookCase>
Remove StoryHeadlineVariations stories

2023-03-20 12:22 UTC, mutebg commented on src/headline/__tests__/headline.stories.tsx
> +        </H1>
Here you should use Headline instead of H1, the same for the rest of the stories, this story is about Headline component, so not use H1/2/3 and so on

2023-03-21 04:05 UTC, mutebg reviewed
now looks better, but we don't have an example with kicker prop and kiker prop overrides

2023-03-21 11:16 UTC, JohnTParsons approved these changes

2023-03-21 11:36 UTC, mutebg commented on src/headline/__tests__/headline.stories.tsx
> +  paddinginline: 'space030';
You can remove these, they don't do anything, or you can use `<Block marginBlock="space030" ...` and so on

2023-03-21 13:46 UTC, mutebg approved these changes

2023-03-21 15:37 UTC, merged