docs(PPDSC-2690): update drawer storybook
newscorp-ghfb/NewsKit pull request #716
Opened 2023-03-21 12:39 UTC by mutebg

PPDSC-2690

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-03-21 12:52 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/ppdsc-2690-update-drawer-stories
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/ppdsc-2690-update-drawer-stories/storybook

2023-03-23 13:08 UTC, Vanals submitted a review, later dismissed

2023-03-23 15:08 UTC, JohnTParsons approved these changes

2023-03-23 15:10 UTC, JohnTParsons requested changes
Spelling of DRAWER_HEADER

2023-03-23 15:10 UTC, JohnTParsons commented on src/drawer/__tests__/drawer.stories.tsx
> +const DRAWER_HEDER = 'Drawer Title';
Spelling: DRAWER_HEADER

2023-03-24 04:00 UTC, mutebg commented on src/drawer/__tests__/drawer.stories.tsx
> +const DRAWER_HEDER = 'Drawer Title';
thanks updated

2023-03-24 06:31 UTC, JohnTParsons approved these changes

2023-03-24 09:21 UTC, Vanals approved these changes

2023-03-24 12:51 UTC, merged