feat(PPDSC-2859): use newskit-website theme from publisher
newscorp-ghfb/NewsKit pull request #718
Opened 2023-03-21 15:35 UTC by LukeFinch

PPDSC-2859

**What**

**Background - why this is needed**
Uses themes from the newskit-themes-publisher repo for the docs site. 

**What did you do**
- Import website themes from the publisher
- Remove old website themes data
- Update tests, we no longer need to check for overrides, as they are contained in the theme package
- Changed some on-site components to line up with expectations from design

**What does the reviewers should expect**
Design changes have been manually checked and approved
Snapshot updates are mostly due to px changing to rem & hex codes coming in lower case
I've removed a test 

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-04-03 09:45 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/ppdsc-2859-use-theme-from-publisher
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/ppdsc-2859-use-theme-from-publisher/storybook

2023-04-14 12:25 UTC, Vanals commented on site/theme/__tests__/doc-theme.test.ts
> -    it(`should not override ${themeName} uneccessarily`, () => {
Is this not needed anymore?

2023-04-14 12:29 UTC, Vanals commented on site/theme/doc-theme.ts
> +  baseTheme: newskitLightTheme, // TODO: Use newsKitTheme from Publisher eventually
Should you  make ticket for this? in case we forget?
Sounds an extra good step for testing how user would implement it.

Even if, in this scenarion I think we do not need to specify newskitLight as it is the default base theme inside the function, am I wrong?

2023-04-14 12:31 UTC, LukeFinch commented on site/theme/__tests__/doc-theme.test.ts
> -    it(`should not override ${themeName} uneccessarily`, () => {
We had a lot of extra overrides as part of the docs themes, which we now include in the themes themselves.
I don't see this being needed anymore – It was testing unused constants

2023-04-14 12:31 UTC, LukeFinch commented on site/theme/doc-theme.ts
> +  baseTheme: newskitLightTheme, // TODO: Use newsKitTheme from Publisher eventually
Will add it to the backlog 👍

2023-04-14 12:32 UTC, Vanals commented
Left a few comments but the rest looks good. If we wasn't checked already could you also double check the SVG Previewer is behaving as expected? it uses all the doc site theme to preview the SVGs. It should correctly import and use the themes for displaying the SVG.
See `colors-theme-list.tsx`

2023-04-14 12:55 UTC, LukeFinch commented
> Left a few comments but the rest looks good. If wasn't checked already could you also double check the SVG Previewer is behaving as expected? it uses all the doc site theme to preview the SVGs. It should correctly import and use the themes for displaying the SVG. See `colors-theme-list.tsx`

good callout - I will double-check. 
In theory - if it's importing the exports from docs-theme.ts it should be fine

2023-04-14 14:23 UTC, jps requested changes

2023-04-14 14:23 UTC, jps commented on site/components/__tests__/__snapshots__/enum-table.test.tsx.snap
> +  font-family: DM Sans;
have you got anything I can read on why we've chosen to get rid of the fallback fonts?

2023-04-14 14:23 UTC, jps commented on site/components/__tests__/__snapshots__/enum-table.test.tsx.snap
> +  font-size: 0.875rem;
How much have we tested this change to REM? I'm not sure if this is something we can just sneak in... 

Here is what the homepage looks like with a larger font size. 

![image](https://user-images.githubusercontent.com/350953/232071169-b12de5db-d9c7-4902-83a3-039307831069.png)

I would suggest we got back to px and look at this change separately.

2023-04-14 14:31 UTC, jps commented on site/theme/doc-theme.ts
> +// Now they are the same as the default theme
should we just get rid of this theme if it's not actually any different?

2023-04-14 14:42 UTC, Vanals commented on package.json
> +    "@newskit-themes/newskit-website": "^1.0.0",
Yeah I was thinking the same.. 🤔  I would avoid using ^ symbol in general tbh. We can stick with the specific version, I am not sure how NPM decides  which version but yeah we can replace it with `"1.0.0"`

2023-04-14 16:15 UTC, LukeFinch commented on package.json
> +    "@newskit-themes/newskit-website": "^1.0.0",
Resolved in lastest commit - changes version to 1.0.1

2023-04-14 16:16 UTC, LukeFinch commented on site/components/__tests__/__snapshots__/enum-table.test.tsx.snap
> +  font-family: DM Sans;
Resolved with 1.0.1 of `@newskit-themes/newskit-website`

2023-04-14 16:17 UTC, LukeFinch commented on site/components/__tests__/__snapshots__/enum-table.test.tsx.snap
> +  font-size: 0.875rem;
@nathanparris – This will require us updating the theme in tokens studio

2023-04-18 10:36 UTC, jps commented on site/components/__tests__/__snapshots__/enum-table.test.tsx.snap
> +  font-size: 0.875rem;
Will be resolved by https://github.com/newscorp-ghfb/newskit-themes-publisher/pull/114

2023-04-19 09:56 UTC, jps approved these changes

2023-04-19 10:29 UTC, Vanals commented
LGTM

2023-04-19 10:29 UTC, Vanals approved these changes

2023-04-19 11:07 UTC, merged