docs(PPDSC-2702): updated stories
newscorp-ghfb/NewsKit pull request #738
Opened 2023-03-22 16:01 UTC by mstuartf

[PPDSC-2702](https://nidigitalsolutions.jira.com/browse/PPDSC-2702)

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-03-22 16:13 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/ppdsc-2702-fieldset-stories
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/ppdsc-2702-fieldset-stories/storybook

2023-03-28 13:41 UTC, JohnTParsons approved these changes

2023-03-29 03:42 UTC, mutebg requested changes

2023-03-29 03:42 UTC, mutebg commented on src/fieldset/__tests__/fieldset.stories.tsx
> +    <Block>
there are components which can be used to have consistent stories across all pages.
```
<StorybookPage columns="...">
<StorybookCase title="Small"> your case</StorybookCase>
<StorybookCase title="Medium"> your case</StorybookCase>
<StorybookCase title="Large"> your case</StorybookCase>
</StorybookPage>
```

2023-03-30 03:48 UTC, mutebg approved these changes

2023-03-31 14:57 UTC, merged