docs(728) - Toast component update scenarios - storybook
newscorp-ghfb/NewsKit pull request #820
Opened 2023-04-11 06:46 UTC by jannuk59

[#728](https://github.com/orgs/newscorp-ghfb/projects/15/views/4?pane=issue&itemId=23592946)

**What**

1. Toast Component scenario updates in storybook

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-04-11 07:01 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/728-update-toast-component-storybook-scenarios
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/728-update-toast-component-storybook-scenarios/storybook

2023-04-18 07:31 UTC, mutebg commented on src/toast/__tests__/toast.stories.tsx
> +        />
you can create a div with z-index if you want.
```
const Container = styled.div`z-inde: 1`;
///
<Container>
<ToastProvider
          autoHideDuration={1000}
          verticalOffset="10px"
          horizontalOffset="10px"
          position="bottom-center"
        />
</Container>
```

2023-04-21 14:27 UTC, JohnTParsons commented on src/toast/__tests__/toast-e2e-stories.tsx
> +  title: 'Components/toast-e2e-hidden',
@mstuartf Bit confused as we copied this approach from Stoyan's 'Components/toast-e2e-hidden', as the hope was it would completely hide the story (not just from side menu), except when running as part of a cypress test. And that seems to work on pipeline but not when running cypress locally.

2023-04-21 14:47 UTC, JohnTParsons commented on src/toast/__tests__/toast-e2e-stories.tsx
> +export const StoryToastE2Etest = () => {
I agree

2023-04-21 14:47 UTC, JohnTParsons commented on src/toast/__tests__/toast-e2e-stories.tsx
> +StoryToastE2Etest.storyName = 'toast-e2e-test';
I agree

2023-04-21 14:49 UTC, JohnTParsons commented on src/toast/__tests__/toast-e2e-stories.tsx
> +  title: 'Components/toast-e2e-hidden',
@jannuk59 On the other hand, the changes Mike suggests correspond to what I did to make 'Component/tooltip-e2e' work, have first failed to get a 'Component/tooltip-e2e-hidden' to work for me locally.

2023-04-24 10:47 UTC, JohnTParsons requested changes

2023-04-24 10:47 UTC, JohnTParsons commented on src/toast/__tests__/toast-e2e.stories.tsx
> +StoryToastE2EtestHidden.storyName = 'Default';
StoryToastE2EHidden would be a better name than StoryToastE2EtestHidden

2023-04-24 11:44 UTC, JohnTParsons approved these changes

2023-04-25 08:33 UTC, mstuartf approved these changes

2023-04-25 12:57 UTC, merged