chore(805): nx and rspack on existing project structure
newscorp-ghfb/NewsKit pull request #847
Opened 2023-04-21 14:19 UTC by JohnTParsons

close #805

**What**

1. Background - speed up
2. What did you do - added nx and rspack on existing project structure
3. What does the reviewers should expect - faster lint and unit test

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-04-21 14:30 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/805-nx-rspack
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/805-nx-rspack/storybook

2023-04-28 10:58 UTC, mutebg approved these changes

2023-04-28 12:48 UTC, Vanals commented on package.json
> +    "test:unit:comps:experimental": "NODE_OPTIONS=\"--max-old-space-size=8192\" npx nx test newskit-ui --codeCoverage --logHeapUsage --coverage --coverageReporters=lcov --coverageReporters=text",
whar are the experimental for? Also do we need the legacy scripts still?  we got so many, I wonder if can be cleaned

2023-04-28 13:47 UTC, JohnTParsons commented on package.json
> +    "test:unit:comps:experimental": "NODE_OPTIONS=\"--max-old-space-size=8192\" npx nx test newskit-ui --codeCoverage --logHeapUsage --coverage --coverageReporters=lcov --coverageReporters=text",
I'd like to keep the experimental versions (for now), as they become the preferred commands at some point. They aren't at the moment as don't seem to give better performance than the other new ones.

I'd like to keep just the two legacy command for now, in case they are reliability or speed issues that show up post-merge. When we have been using this new nx-rspack approach for a month without issue, then those two could be removed.

2023-04-28 13:50 UTC, Vanals approved these changes

2023-04-28 14:24 UTC, merged

2023-04-28 14:36 UTC, jps requested changes

2023-04-28 14:36 UTC, jps commented on src/tsconfig.spec.json
> +    "src/**/*.spec.jsx",
```suggestion
    "src/**/*.{test,spec}.{ts,tsx,js,jsx}"
```

2023-04-28 14:36 UTC, jps commented on src/.eslintrc.json
> +    }
are these overrides obsolete ass they don't have any rules?

2023-04-28 14:36 UTC, jps commented on site/project.json
> +        "production": {}
is an output path required here?

2023-04-28 14:36 UTC, jps commented on site/.eslintrc.json
> +    }
again, not sure these are doing anything.

2023-04-28 14:36 UTC, jps commented on package.json
> +    "lint:legacy": "concurrently --names \"code,markdown,next\" \"scripts/assert-files-and-folders.js && yarn lint:code:base .\" \"yarn markdownlint -c ./.markdownlint.json *.md **/*.md\" \"yarn next
suspect these legacy ones will be removed?

2023-04-28 14:36 UTC, jps commented on .eslintrc.json
> +    }
are these required?

2023-04-28 14:36 UTC, jps commented on package.json
> +    "test:unit:run": "NODE_OPTIONS=\"--max-old-space-size=8192\" nx exec -- jest --logHeapUsage --coverage --coverageReporters=lcov --coverageReporters=text",
given you've bumped the CI instance size should this memory size go up also?