Docs(822) Card Composable doc site
newscorp-ghfb/NewsKit pull request #876
Opened 2023-05-05 08:18 UTC by jannuk59

#822 

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-05-05 08:38 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/822-card-composable-doc-site
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/822-card-composable-doc-site/storybook

2023-05-17 09:01 UTC, mutebg requested changes

2023-05-17 09:01 UTC, mutebg commented on site/pages/components/card-composable.tsx
> +            'Props and Overrides same as GridLayout + can have stylePreset and transitionPreset as an override',
I would delete this summary and add props & overrides same way as CardComposable component

2023-05-18 08:29 UTC, mutebg requested changes

2023-05-18 08:29 UTC, mutebg commented on site/pages/components/card-composable.tsx
> +            'Props and Overrides same as CardComposable + can have stylePreset and transitionPreset as an override',
Remove this one

2023-05-18 08:29 UTC, mutebg commented on site/pages/components/card-composable.tsx
> +            'Props and Overrides same as CardComposable component + can have stylePreset and transitionPreset as an override',
Remove this one

2023-05-18 08:29 UTC, mutebg commented on site/pages/components/card-composable.tsx
> +            'Props and Overrides same as CardComposable component + can have stylePreset and transitionPreset as an override',
Remove this one

2023-05-18 08:29 UTC, mutebg commented on site/pages/components/card-composable.tsx
> +          summary: 'Props & Overrides same as StandaloneLink',
Remove this one

2023-05-18 08:29 UTC, mutebg commented on site/pages/components/card-composable.tsx
> +          propsRows: [
I think its better to add other pross and overrides, take a look at the types file, that apply to all Card components

2023-05-18 09:54 UTC, jannuk59 commented on site/pages/components/card-composable.tsx
> +          propsRows: [
@mutebg Do we need to add props and overrides from standaloneLink component?

2023-05-18 11:31 UTC, mutebg requested changes

2023-05-18 11:31 UTC, mutebg commented on site/pages/components/card-composable.tsx
> +            {
can you store all these props and overrides in consts so that they can be re-used across all components? 
Also, CardComposable  needs same props.
Apart from that, everything else seems good and ready for approval, thank you

2023-05-19 06:58 UTC, mutebg commented on site/pages/components/card-composable.tsx
> -            },
You need to reverse the `media` prop

2023-05-19 06:58 UTC, mutebg commented on site/pages/components/card-composable.tsx
> +              default: 'cardContainer',
CardAction does not have default stylePreset and transitionPreset

2023-05-19 06:58 UTC, mutebg commented on site/pages/components/card-composable.tsx
> +              default: 'cardContainer',
CardContent does not have default stylePreset and transitionPreset

2023-05-19 06:58 UTC, mutebg commented on site/pages/components/card-composable.tsx
> +            },
CardMedia does not have default stylePreset and transitionPreset

2023-05-19 06:58 UTC, mutebg commented on site/pages/components/card-composable.tsx
> +            },
you need to add expand prop

2023-05-19 08:41 UTC, mutebg approved these changes

2023-05-19 08:41 UTC, mutebg approved these changes

2023-05-19 08:49 UTC, JohnTParsons approved these changes

2023-05-19 09:09 UTC, merged