feat(806) container queries and storybook
newscorp-ghfb/NewsKit pull request #877
Opened 2023-05-05 09:03 UTC by LukeFinch

closes #806 

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-05-05 10:42 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/806-container-queries-storybook
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/806-container-queries-storybook/storybook

2023-05-05 14:58 UTC, JohnTParsons requested changes

2023-05-05 15:24 UTC, LukeFinch commented on src/block/__tests__/block.stories.tsx
> +      // stylePreset="blockDefault"
Ah - needs to be uncommented. Thanks!

2023-05-09 11:06 UTC, jps requested changes

2023-05-09 12:45 UTC, LukeFinch commented on src/block/__tests__/block.stories.tsx
> +    ${getColorCssFromTheme('borderColor', 'blue060')}
Will amend 👍

2023-05-09 12:47 UTC, LukeFinch commented on src/block/block.tsx
> +  ${({containerName}) => containerName && `container-name: ${containerName}`}
Possibly, if we need to add these two props into more components in the future, it would make sense to do that I guess.

2023-05-09 12:47 UTC, LukeFinch commented on src/utils/style/types.ts
> +export type ResponsiveValue<T> = MQ<T> | CSSQueryRules<T>;
Sure thing

2023-05-10 10:17 UTC, mstuartf commented on src/grid-layout/__tests__/stories/grid-layout.stories.tsx
> +      <StorybookCase title="Container query < 200px">
Is it possible to make the titles of these a little more descriptive? I thought for a while this was supposed to do something responsive. But now I see they have the same container query but different size container. I think the titles are a bit misleading atm.

2023-05-10 10:17 UTC, mstuartf commented on src/grid-layout/__tests__/stories/grid-layout.stories.tsx
> +      <StorybookCase title="Container query < 200px">
Also would it make more sense to swap the logic for the two containers? Typically I would expect columns to be split into rows as the container gets smaller, not the other way around.

2023-05-10 10:18 UTC, mstuartf commented on src/grid-layout/__tests__/stories/grid-layout.stories.tsx
> +      <StorybookCase title="Container query < 200px">
Looking at the other stories, I think it's as simple as changing the titles to `Container < Xpx`. The query is the same, only the container width changes.

2023-05-10 10:18 UTC, mstuartf commented
👏 This is cool

2023-05-10 12:25 UTC, LukeFinch commented on src/grid-layout/__tests__/stories/grid-layout.stories.tsx
> +      <StorybookCase title="Container query < 200px">
Sounds good! I agree - will push those suggestions.

2023-05-11 08:25 UTC, mutebg commented on src/grid-layout/__tests__/stories/grid-layout.stories.tsx
> +`;
if the block already supports container type and name, why not pass it as prop instead of styled it.

2023-05-11 08:25 UTC, mutebg commented on src/card-composable/__tests__/__stories/card-composable.stories.tsx
> +`;
I guess you can use styled(block) or just GridLayout with 
`<GridLayout overides={{width: 400}} containerType="inline-size" />`

2023-05-11 08:25 UTC, mutebg commented on src/grid-layout/types.ts
> +} & ContainerQueryProps &
The Block already have these as "overrides' which I mentioned need to be just props. 
And this is adding it second time,

2023-05-11 08:25 UTC, mutebg commented on src/grid-layout/types.ts
> +    ContainerQueryProps;
same as block -> move to props

2023-05-11 08:25 UTC, mutebg commented on src/utils/responsive-helpers.ts
> +// };
this can be removed

2023-05-11 08:25 UTC, mutebg commented on src/utils/style/types.ts
> +export type ResponsiveValue<T> = MQ<T> | CSSQueryRules<T>;
We need to update the docs site as well so that reflects these changes.

2023-05-11 08:25 UTC, mutebg commented on src/utils/style/types.ts
> +  rule: `@media ${string}` | `@container ${string}`;
that's very clever ;)

2023-05-11 08:25 UTC, mutebg commented on src/utils/style/utils.ts
> +
Do you need this function, I can't see any where been used?

2023-05-12 16:05 UTC, LukeFinch commented on src/utils/style/utils.ts
> +
Leftover from when I was trying to make custom stuff. thanks for catching

2023-05-12 16:09 UTC, LukeFinch commented on src/block/__tests__/block.stories.tsx
> +          }}
Originally I had them as props, @jps  suggested moving them into overrides - to be the same level as logical props
Ideally would keep them consistent across all components

2023-05-15 08:08 UTC, mutebg commented on src/block/__tests__/block.stories.tsx
> +          }}
Well, the thing is that Block does not have overrides, so the logical props on the Block are props, `<Block marginInline />`
GridLayout has overrides (which was wrong) and in that case they can be part of the overrides

2023-05-15 08:15 UTC, JohnTParsons approved these changes

2023-05-16 14:42 UTC, jps commented on package.json
> +    "@emotion/styled": "^11.10.5",
`11.10.4` will be the lowest supported version can we please update the peer dependencies?

2023-05-16 14:59 UTC, jps commented on src/utils/logical-properties.ts
> +  marginInlineStart?: ResponsiveValue<string>;
One slight concern here is this now implies all components with logical props now support container queries and it won't be clear to users which is actually do. Maybe we just have to bite the bullet for now and the other components can be updated soon as aware this PR could keep growing. 

Just a reminder we are going to need to update the docs also to reflect the change from MQ to ResponsiveValue

2023-05-19 11:24 UTC, mutebg submitted a review, later dismissed

2023-05-19 11:49 UTC, mutebg approved these changes

2023-07-04 12:55 UTC, JohnTParsons approved these changes

2023-07-17 07:38 UTC, mutebg commented
Since we are changing PEER DEPS I am not sure if that's not a breaking change for all users

2024-11-25 08:33 UTC, closed without merging