docs(723): Standfirst Storybook Enhancement
newscorp-ghfb/NewsKit pull request #881
Opened 2023-05-08 14:53 UTC by jannuk59

#723 

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-05-08 15:03 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/723-standfirst-storybook
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/723-standfirst-storybook/storybook

2023-05-10 08:02 UTC, mutebg requested changes

2023-05-10 08:02 UTC, mutebg commented on src/standfirst/__tests__/standfirst.stories.tsx
> +            typographyPreset: 'utilitySubheading020',
When is default I am expecting it not to have any overrides

2023-05-10 08:02 UTC, mutebg commented on src/standfirst/__tests__/standfirst.stories.tsx
> +              stylePreset: 'standfirstCustom',
You can use directly `inkBrand010` as style-preset, not need to create a custom one, newskit automatically creates style presets for all colors tokens which start with `ink`
```suggestion
              stylePreset: 'inkBrand010',
```

2023-05-12 03:57 UTC, mutebg commented on src/standfirst/__tests__/standfirst.stories.tsx
> +);
Why do you use text-block with typographyPreset to pass it down to the standfirst component?
Is that required by design? if so this needs to change, that's not correct

2023-05-12 03:58 UTC, mutebg commented on src/standfirst/__tests__/standfirst.stories.tsx
> +      <Standfirst as="h2">{CONTENT}</Standfirst>
since this is default story, I would remove as="h2" prop

2023-05-12 08:26 UTC, jannuk59 commented on src/standfirst/__tests__/standfirst.stories.tsx
> +);
@mutebg as per design its `typographyPreset="utilitySubheading020"` by default we have 
```
typographyPreset: {
        xs: 'editorialSubheadline010',
        lg: 'editorialSubheadline020',
},
```
So I have added text-block component to update the typographyPreset

2023-05-12 08:39 UTC, mutebg commented on src/standfirst/__tests__/standfirst.stories.tsx
> +);
the designs are wrong, the default version is without any props and overrides

2023-05-15 08:16 UTC, JohnTParsons approved these changes

2023-05-15 08:56 UTC, nathanparris commented on src/standfirst/__tests__/standfirst.stories.tsx
> +);
@mutebg @jannuk59 The standfirst already has typography presets in the defaults, so there shouldn't be any need to add these to a content text block.

2023-05-15 09:06 UTC, mutebg commented on src/standfirst/__tests__/standfirst.stories.tsx
> +);
@nathanparris this exactly what I meant. thanks for clarifying it

2023-05-15 13:35 UTC, jannuk59 commented on src/standfirst/__tests__/standfirst.stories.tsx
> +);
done @mutebg @nathanparris. By default will be having 
```
typographyPreset: {
        xs: 'editorialSubheadline010',
        lg: 'editorialSubheadline020',
},
```

2023-05-15 13:44 UTC, mutebg approved these changes

2023-05-15 13:44 UTC, mutebg approved these changes

2023-05-16 05:13 UTC, JohnTParsons approved these changes

2023-05-16 08:28 UTC, mutebg approved these changes

2023-05-16 08:37 UTC, merged