chore(871): snapshot test package.json
newscorp-ghfb/NewsKit pull request #885
Opened 2023-05-10 08:01 UTC by JohnTParsons

closes #871

**What**

1. Background - as a reminder to devs to keep dependenciesNotToBeIncluded up-to-date
2. What did you do - add test
3. What does the reviewers should expect - snapshot test to fail if/when package.json changes

**I have done:**
- [x] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

2023-05-10 08:11 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/871-test-package
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/871-test-package/storybook

2023-05-10 08:43 UTC, mutebg submitted a review, later dismissed

2023-05-10 10:08 UTC, Vanals submitted a review, later dismissed

2023-05-10 14:27 UTC, jps requested changes

2023-05-10 14:27 UTC, jps commented on src/__tests__/__snapshots__/package.test.ts.snap
> +    "@newskit-themes/the-sun": "^0.1.0",
these can be excluded

2023-05-10 14:27 UTC, jps commented on src/__tests__/package.test.ts
> +describe('package.json updated', () => {
Good idea adding this test in 🏅

2023-05-11 08:45 UTC, JohnTParsons commented on src/__tests__/__snapshots__/package.test.ts.snap
> +    "@newskit-themes/the-sun": "^0.1.0",
Done

2023-05-11 09:26 UTC, mutebg approved these changes

2023-05-12 10:25 UTC, jps approved these changes

2023-05-12 14:32 UTC, merged