fix(#905): support fontMetrics embedded in typograpyPresets.json #905
newscorp-ghfb/NewsKit pull request #906
Opened 2023-07-07 16:32 UTC by dj-kmuldoon

Supports both current NewsKit parsing of fontMetrics and pre-parsed fontMetrics in typographyPreset for djds-themes-publisher

closes #000

**What**

1. Background - why this is needed
2. What did you do
3. What does the reviewers should expect

**I have done:**
- [Y] Written unit tests against changes
- [N] Written functional tests against the component and/or NewsKit site
- [N] Updated relevant documentation

**I have tested manually:**
//
// Changes are foundational rather than component specific...
//
- [N] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [N] The screen reader reads and flows through the elements as expected.
- [N] There are no new errors in the browser console coming from this PR.
- [N] When a visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [N] The Playground feature is working as expected

2023-07-10 15:00 UTC, JohnTParsons requested changes
Looks fine, just minor edits to test syntax suggested

2023-07-10 15:00 UTC, JohnTParsons commented on src/utils/__tests__/get-font-metrics.test.ts
> +    expect(getFontMetrics(typographyPreset, {})).toBe(undefined);
NK developers usually used the `.toBeUndefined()` jest function for this

2023-07-11 06:41 UTC, mutebg reviewed
Thanks for the PR.

Also, on later stage can you please rename the branch to `feat/905-fontMetrics-for-djds-themes-publisher-format` in that way our release bot can make proper release

2023-07-11 06:41 UTC, mutebg commented on src/utils/style/helpers/getter-helper.ts
> +  }
```suggestion
 if ( fontMetrics && isFontMetricsObject(fontMetrics) )  return true;
 
 console.warn(`No default fontMetrics found for '${fontFamily}'.`);
 return false;

```

2023-07-11 06:41 UTC, mutebg commented on src/utils/__tests__/get-font-metrics.test.ts
> +describe('getFontMetrics with fontMetrics embedded in typographyPreset', () => {
To be honest I am not sure if these tests are needed.
In my understanding getFontMetrics is not supposed to be used as a separate unit and its internal to getTypographyPresetFromTheme.  Because of that, I prefer to have tests on `getTypographyPresetFromTheme` that cover the cases with fonts-metrics embedded inside typographyPreset. That can be done in typography-preset.test.tsx`

2023-07-11 06:41 UTC, mutebg commented on src/utils/style/helpers/getter-helper.ts
> +  return fontMetrics.fontWeight010 ? fontMetrics.fontWeight010 : fontMetrics;
Do we need to support other font weights?

2023-07-11 06:41 UTC, mutebg commented on src/utils/style/getters.ts
> +  const deprecatedApplyCrop = (typographyPreset: any) => {
Can you push this part as well

2023-07-11 06:41 UTC, mutebg commented on src/utils/__tests__/get-font-metrics.test.ts
> +};
This has not been used anywhere

2023-07-11 06:41 UTC, mutebg commented on src/utils/style/helpers/getter-helper.ts
> +  }
can you move this function before been used, I am sure we had lint rule for all functions to be defined before being used. It makes is harder to read in that way

2023-07-11 10:39 UTC, dj-kmuldoon commented on src/utils/style/helpers/getter-helper.ts
> +  return fontMetrics.fontWeight010 ? fontMetrics.fontWeight010 : fontMetrics;
We do not need to support other font weights (or even 'fontWeight010') when the NewsKit format is processed via djds-themes-publisher. I only add fontWeight010 as protection for legacy manually typed code.

```
  // 1. If fontMetrics are embedded in typographyPreset, return fontMetrics
  if (fontMetrics) {
    return parseFontMetrics(fontMetrics);
  }
```

2023-07-11 10:49 UTC, dj-kmuldoon commented on src/utils/__tests__/get-font-metrics.test.ts
> +};
I've removed because fontMetrics embedded in typograph-preset.json is auto-generated via djds-themes-publisher, which cannot malform the outuput.

2023-07-11 11:01 UTC, dj-kmuldoon commented on src/utils/__tests__/get-font-metrics.test.ts
> +describe('getFontMetrics with fontMetrics embedded in typographyPreset', () => {
I think you're correct that getTypographyPresetFromTheme covers the scenario. Yet, I think the snapshots used in typography-preset.test.tsx are more 'systems testing' so it seemed best to make getFontMetrics it's own test suite since it's more of a 'unit test'.

2023-07-11 12:26 UTC, JohnTParsons submitted a review, later dismissed

2023-07-11 13:37 UTC, mutebg commented on src/utils/__tests__/get-font-metrics.test.ts
> +describe('getFontMetrics with fontMetrics embedded in typographyPreset', () => {
I agree with what you are saying but at the same time you want to test how consumers test the function, and in that case, consumers are using getTypographyPresetFromTheme, so having said that IMO is better to create a theme with your typography presets and test that getTypographyPresetFromTheme returns correct values from that theme.

2023-07-11 13:39 UTC, mutebg commented on src/utils/__tests__/get-font-metrics.test.ts
> +// yarn jest src/utils/__tests__/get-font-metrics.test.ts
FYI: you can run `yarn test:unit:watch` and after the script runs you press "P" and filter the test by name

2023-07-11 14:41 UTC, dj-kmuldoon commented on src/utils/__tests__/get-font-metrics.test.ts
> +describe('getFontMetrics with fontMetrics embedded in typographyPreset', () => {
Yes, I understand now! Thanks! And I agree as well. If all the same, let's keep get-font-metrics.test.ts as is, but add a proper test in typography-preset.test.tsx as you describe!

2023-07-11 14:42 UTC, dj-kmuldoon commented on src/utils/__tests__/get-font-metrics.test.ts
> +// yarn jest src/utils/__tests__/get-font-metrics.test.ts
Much appreciated! These tips/tricks are exactly what I need.

2023-07-12 12:52 UTC, mutebg reviewed
LGTM, can you please create a new branch `feat/905-fontMetrics-for-djds-themes-publisher-format` so that CI can be triggered

2023-07-13 08:21 UTC, JohnTParsons approved these changes

2023-07-18 11:53 UTC, closed without merging