feat(WWP-3314): add gpp stub file to consent
newscorp-ghfb/NewsKit pull request #924
Opened 2023-10-23 09:50 UTC by kboeff

https://nidigitalsolutions.jira.com/browse/WWP-3314
## What

<b>Background</b> - why this is needed - Multi-State Privacy Agreement/String (MSPA) is a signal that notifies downstream partners that participating publishers have provided end-users with specific notice and choice over data processing activities on their properties. The Multi State Privacy Agreement is now available to implement on our properties alongside the U.S. Privacy String (USPS) with the intention that the MSPS will eventually supplant USPS later in the year.

<b>What did you do</b> - Updated `Consent` component to include the GPP stub file.

I have done:
- Written unit tests against changes
- Written functional tests against the component and/or NewsKit site
- Updated relevant documentation

I have tested manually:
 The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
 The screen reader reads and flows through the elements as expected.
 There are no new errors in the browser console coming from this PR.
 When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
 The Playground feature is working as expected
Before:

After:

Who should review this PR:

How to test:

2023-10-23 09:59 UTC, pp-serviceaccount commented
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/wwp-3314
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/wwp-3314/storybook

2023-10-25 08:08 UTC, lhaggar requested changes

2023-10-25 08:08 UTC, lhaggar commented on site/pages/components/consent.mdx
> +    To enable default MSPA configuration the gpp flag should be added (gpp: true) and ccpa object should contain 'includeGppApi' parameter set to 'true'. Instructions and additional MSPS settings can
Why do we need to set a boolean on the root (`gpp`) and also in the ccpa object (`ccpa.includeGppApi`)? Can we not just set in one place and have the component do what it needs?

2023-10-25 08:08 UTC, lhaggar commented on site/pages/components/consent.mdx
> +      <Prop name="includeGppApi" type="object">
Duplicate here, its a boolean above and an object here?

2023-10-25 08:08 UTC, lhaggar commented on site/pages/components/consent.mdx
> +    <Prop name="gpp" type="boolean">
This prop is on the root of the component but nested under the ccpa object here in the docs.

2023-10-25 09:10 UTC, kboeff commented on site/pages/components/consent.mdx
> +    To enable default MSPA configuration the gpp flag should be added (gpp: true) and ccpa object should contain 'includeGppApi' parameter set to 'true'. Instructions and additional MSPS settings can
That makes sense, we can just use `ccpa.includeGppApi`.

2023-10-25 10:31 UTC, lhaggar requested changes

2023-10-25 10:31 UTC, lhaggar commented on src/consent/types.ts
> +    includeGppApi?: boolean;
Sorry, was looking at the docs more and I think we still need to support the object version of this prop too. Some clients may wish to customise this rather than just use the defaults. Think it should be `true | MSPATransactions` where that secondary type is:
```
export interface MSPATransactions {
  MspaCoveredTransaction: 'yes' | 'no';
  MspaOptOutOptionMode: 'yes' | 'no' | 'na';
  MspaServiceProviderMode: 'yes' | 'no' | 'na';
}
```
In terms of the docs, put the type as `true | MSPATransactions`, can link to the docs for more info on the MSPATransactions, think that should be ok.

2023-10-31 16:51 UTC, lhaggar requested changes
Checked the docs page and a minor change is needed, but otherwise think it's looking good!

2023-10-31 16:51 UTC, lhaggar commented on site/pages/components/consent.mdx
> +        MSPS settings could be customized by passing configuration object to the includeGppApi as [shown here](https://docs.sourcepoint.com/hc/en-us/articles/18007731422099-Enable-GPP-Multi-State-Pri
![image](https://github.com/newscorp-ghfb/NewsKit/assets/13315161/fefc42eb-ab42-4b7f-8e2f-b699e7090f49)

This needs changing to an <a> tag, you can see in the site preview it is rendering this markup as is. MDX is a funny mix, the markdown syntax won't work from inside React components, only on the root. See below for example under the "reactHelmet" prop.

2023-11-02 16:29 UTC, lhaggar submitted a review, later dismissed

2024-01-17 15:47 UTC, lhaggar requested changes

2024-01-17 15:47 UTC, lhaggar commented on src/consent/types.ts
> +export interface MSPATransactions {
Think this should probably be changed for consistency with its properties.
```suggestion
export interface MspaTransactions {
```

2024-01-18 07:05 UTC, kboeff commented on src/consent/types.ts
> +    includeUspApi?: boolean;
Actually the new flag is of type `boolean`, so I'll update the docs only.

2024-01-18 07:09 UTC, kboeff commented on src/consent/types.ts
> +export interface MSPATransactions {
Good catch, but this type is no longer needed.

2024-01-23 10:48 UTC, lhaggar approved these changes

2024-01-23 11:45 UTC, antoanetad78 approved these changes

2024-01-23 12:08 UTC, ayush04 approved these changes

2024-01-24 13:21 UTC, lhaggar approved these changes

2024-02-29 10:09 UTC, lhaggar approved these changes

2024-02-29 15:49 UTC, ayush04 approved these changes

2024-03-01 14:02 UTC, merged